### ISSUE TITLE
Benutzer lässt sich nicht speichern

### ISSUE THREAD

**Issue by Triox85** [Apollon77/ioBroker.meross#106]
Hallo Apollo.
Ich habe den Adapter Meross über die Instanz gelöscht.
Beim erneuten Installieren des Adapters ist es nicht möglich die Anmeldedaten zu speichern.
Wenn alles eingegeben wurden und ich auf Speichern oder Speichern und schließen klicke passiert nichts. Wenn ich auf Abbrechen klicken wird abgefragt ob man die Eingaben verwerfen möchte.
Unter Log kommt nur der Fehler:
(2901) Meross Connection Error: Error: 1000: Lack user

Js-Controller 3.1.4
Node.js v12.16.3
NPM6.14.4
ioBroker fix ist ausgeführt

**Comment by Ricox1975** [comment]
habe die gleichen Probleme.
nach downgrade auf 1.3.12 funktioniert es wieder.

**Comment by Triox85** [comment]
Bei mir leider nicht.
Auch ein wiederherstellen von ioBroker und neu installieren hat nichts gebracht.

**Comment by Triox85** [comment]
Also scheint bei 1.3.13 ein Fehler zu bestehen, der die Eingabe der Daten nicht annimmt.

**Comment by Apollon77** [comment]
test 1.4.0 please

**Comment by Apollon77** [comment]
1.4.1 should solve it finally

**Comment by Triox85** [comment]
Super!
Geht wieder reibungslos.
Danke dir
