### ISSUE TITLE
Meross schaltet den Service ab

### ISSUE THREAD

**Issue by Bibo13** [Apollon77/ioBroker.meross#113]
Hallo zusammen,
Meross hat mir gerade eine Mail geschrieben. Der Adapter ist jetzt auf GELB und nichts läßt sich mehr steuern. Habt Ihr das auch?
Siehe Mail:

Dear Customer, 

This is meross cloud security team contacting you. 
First of all, thanks for purchasing meross and we hope that you enjoy life with our smart products. 
Recently our cloud security system has noticed that your devices are communicating with the could server at an extremely high frequency. We consider these behaviors abnormal and are concerned about the security of your devices. 
Due to the security concerns and the intent to avoid any further potential damage, we will terminate the cloud services of these devices for now. 
If you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to <cloudservice@meross.com>. We will resume cloud service for you within 24 hours. Please note that any abnormal high cloud request frequency will cause cloud service termination again. 
Should you have any information you would like to provide us with or would like to offer us any clarification, please contact us within 24 hours. 

Thanks! 
meross Cloud Security Team

**Comment by Apollon77** [comment]
Du bist der erste der so etwas berichtet. Was genau tust Du denn so mit deinen Geräten in ioBroker? Kann es sein das Du ein "Abfrageintervall für Verbrauchsdaten" angegeben hast? Auf was steht das denn? Default ist eine Abfrage alle 20 Sekunden,hast Du das geändert?

**Comment by Bibo13** [comment]
Es steht bei mir auf 5. Ich denke das kann man auch viel höher setzen. Stromwerte werden sowieso nicht geliefert. Ich gehe mal auf 60. Paralell schreibe ich das cloudservice Team an und lasse den zugang wieder frei schalten.

**Comment by Apollon77** [comment]
.. solltest Du wohl
> no more than one message every ten seconds

Ich baue mal im Adapter ein unteres Limit ein und zwar bei 30

Aber beim Schreiben nix von dem Adapter erzählen oder so!!

**Comment by Bibo13** [comment]
OK. Ich hab mich mal dumm gestellt.

Dear Sir or Madam,
I have 4 MSS310 sockets and 2 socket strips from you that are now no longer switchable. I am not aware that I carry out so many switching operations. I use it to switch lamps on and off. At most 3-5 times a day. 
So what's your shutdown? that can only be a mistake. Please activate the access again.

**Comment by Bibo13** [comment]
Hallo zusammen. Der Cloud-Zugriff ist seit 15:00 kommentarlos wieder Grün.

**Comment by Apollon77** [comment]
I leave open as reminder to increase the defauklt polling interval and add comments

**Comment by gitknd** [comment]
Hallo, 
ich habe heute auch eine solche eMail von Meross bekommen.
Der Abfrageintervall steht auf 30 und das einzige was sich in den letzten Wochen geändert hat, ist die Version des Adapters (immer aktuell gehalten, derzeit 1.12.2
Kann es sein, dass bei den letzten Updates irgendwas dazu beigetragen hat ?

**Comment by Apollon77** [comment]
An sich nicht ... und vor allem: Schalte einfach den lokalen Modus ein dann sollte dieses problem nicht mehr existieren!!

**Comment by Apollon77** [comment]
Dann Bitte mal Debug Log checken was da loióst ist ... an sich sollte damit nichts mehr passieren - oder hast Du geräte die lokal nie erreichrabr sind?

**Comment by gitknd** [comment]
Ich hab die Instanz jetzt mal auf Debug Loglevel geändert. Scheint, als wäre "nur" der Garagenöffner betroffen, denn der wird nun in der App auch als nicht erreichbar dargestellt. Steckdosen funktionieren aber soweit (Stichproben). Allerdings wird der Status ind en Objekten nicht mehr richtig je nach Schaltzustand angezeigt. Ändert sich nicht mehr. 
Worauf kann ich im Log achten ?
Ansonsten sind alle Devices im lokalen Netz.

**Comment by gitknd** [comment]
So, ich habe nun mal im Debug geschaut und die 30s http-local-call Aufrufe gehen an die jeweilige interne IP der Devices. D.h. doch aber auch in dem Falle, dass der Adapter gar nicht mehr mit der Meross Cloud kommuniziert, oder ? Ich frage mich, warum Meross dann die Cloud Services gestoppt hat. Es war wenig Bewegung in den Devices.

**Comment by Apollon77** [comment]
Genau das ist die interessante Frage :-)

**Comment by gitknd** [comment]
So, nachdem mich Meross wieder freigeschaltet hatte, wurde ich heute erneut gesperrt. Zwar hat man mich jetzt wieder freigeschaltet, aber die Ursache für die Sperrung ist mir immer noch nicht klar.  Wobei ich nun auch die neue Version aufgrund des Issues #290 gesehen habe. Vielleicht ist das ja schon die Lösung.

**Comment by gitknd** [comment]
Wenn ich prüfen will, ob mit der Meross Cloud Kontakt über den Adapter aufgenommen wird, dann kann ich das doch an den Einträgen HTTP-Local-Call sehen, oder ? 

Wenn diese so aussehen (wurde von mir etwas maskiert), also eine lokale IP enthalten ist, dann wird nur lokal abgefragt, richtig ? Oder gibt es noch einen anderen Aufruf ?:
HTTP-Local-Call 1908211527735325185548exxxxxxxxxx {"url":"http://192.168.xxx.xxx/config",

**Comment by Apollon77** [comment]
Naja das ist das was WIR tun ... die Frage ist ja was das gerät 8welches ja auch mit der Cloud verbunden ist) mit so einem Call macht und ob dann trotzdem irgendwas in die Cloud geht vom gerät aus ... Annahme war das nicht ...

**Comment by Apollon77** [comment]
@gitknd Welche Abfragefrequenz hast du eingestellt für energiewerte? setz mal auf 30s und schaue ob es wieder passiert. SOnst gern nochmal Log auf debug und mit der allerneuesten version sicherstellen das nur Local-HTTP im Log ist ... (in der neuesten version werden auch MQTT-Cloud-Calls geloggt
