### ISSUE TITLE
Garage Door opener MSG100 noStatus from DoorSensor

### ISSUE THREAD

**Issue by mikewolf** [Apollon77/ioBroker.meross#162]
Hello i`bought the Meross MSG100 door Opener it looks good.
But i see nothing from the DoorSensor in this adapter , in the app froma meross i can see the staus from the DoorSensor
is there a way to integrate it in a Datapoint ???
wirh best regards 
mikewolf

**Comment by Apollon77** [comment]
Please enable debug log and provide the full log of adapter start here or via email to iobroker@fischer.ka.de with reference to this issue here

**Comment by mikewolf** [comment]
hello i send you a mail,with the log from iobroker Debug "admin" and from harddisk log

**Comment by Apollon77** [comment]
Hm, plese send again.I ded not receved the email

**Comment by fupsi42** [comment]
Hi,

I'm not sure if we have the same problem, but when we open the door in ioBroker, the variable 0-garageDoorWorking is updated but always remains false. Is this the feedback contact? Or is there another way to process the feedback contact in the ioBroker?

Thanks
Markus

**Comment by n3ucr0n** [comment]
> Please enable debug log and provide the full log of adapter start here or via email to [iobroker@fischer.ka.de](mailto:iobroker@fischer.ka.de) with reference to this issue here

hello Apollon,
I also installed the garage opener today and miss the data point.
I would like to send you the required log files. Can you please give me a "how to" on how to enable debug mode?

Also, I got the same behaviour like fupsi42: 
The status of the opener can be used, but it always stays on the "False" value. If you set it to "True", the garage door opens, but the status becomes "false" again. Then when I want to close the door, I just have to confirm the datapoint with the value "false" again and the door closes.

Is there maybe a way to indicate in a datapoint that the door is currently opening or closing? This is also displayed in the Meross app.

Thanks for your work!

Kind regards
Micha

Translated with www.DeepL.com/Translator (free version)

**Comment by Apollon77** [comment]
> Is there maybe a way to indicate in a datapoint that the door is currently opening or closing? This is also displayed in the Meross app.

There should be a working state or ?!

>  I would like to send you the required log files. Can you please give me a "how to" on how to enable debug mode?

Admin: Instances - Expert mode - column loglevel set to debug

Please then always grab the log from the logfile on disk (/opt/iobroker/log/...) and NOT admin

**Comment by Apollon77** [comment]
In fact I checked one log and code again.

From Meross only the status "offen" is reported ... The "working" state is set if you control it via adapter because the adapter can then wait untul the "expected" status is reported and will set "working" so long.
