### ISSUE TITLE
Meross 1.0 Adapter startet nicht

### ISSUE THREAD

**Issue by Moormerlander** [Apollon77/ioBroker.meross#20]
Debug Log:

meross.0 | 2019-07-17 12:14:21.190 | debug | system.adapter.admin.0: logging true
meross.0 | 2019-07-17 12:14:18.344 | debug | connected set to false
meross.0 | 2019-07-17 12:14:18.214 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.meross, node: v8.16.0
meross.0 | 2019-07-17 12:14:18.093 | debug | statesDB connected
meross.0 | 2019-07-17 12:14:18.025 | debug | objectDB connected

node.js 8.16.0 installiert

**Comment by sigi2345** [comment]
Bei mir geht er nicht Online:

`

meross.0 | 2019-07-17 12:49:24.621 | debug | Online: undefined
-- | -- | -- | --
meross.0 | 2019-07-17 12:49:04.621 | info | Devices initialized
meross.0 | 2019-07-17 12:49:04.621 | debug | Device Send Raw: 1806295369746429081434298f15a9af - data: {"header":{"from":"/app/65722-2165f65af59119944bcf6b95f9540748/subscribe","messageId":"57a33b7cc7800b406ce81ad80a31bd25","method":"GET","names
meross.0 | 2019-07-17 12:49:04.611 | warn | Can not get Abilities for Device 1806295369746429081434298f15a9af: Error: Timeout
meross.0 | 2019-07-17 12:49:04.611 | debug | 1806295369746429081434298f15a9af Abilities: undefined
meross.0 | 2019-07-17 12:48:44.611 | debug | connected set to true
meross.0 | 2019-07-17 12:48:44.610 | debug | Device Send Raw: 1806295369746429081434298f15a9af - data: {"header":{"from":"/app/65722-2165f65af59119944bcf6b95f9540748/subscribe","messageId":"a2033cb887d37ffbeaf33ffde81c4985","method":"GET","names
meross.0 | 2019-07-17 12:48:44.610 | info | Device: 1806295369746429081434298f15a9af connected
meross.0 | 2019-07-17 12:48:44.429 | debug | {"uuid":"1806295369746429081434298f15a9af","onlineStatus":2,"devName":"Steckdosenleiste Wohnzimmer","devIconId":"device020_eu","bindTime":1541774356,"deviceType":"mss425e","subType":"eu","channels":[{
meross.0 | 2019-07-17 12:48:44.429 | info | Device 1806295369746429081434298f15a9af initialized
meross.0 | 2019-07-17 12:48:43.998 | debug | connected set to false
meross.0 | 2019-07-17 12:48:43.882 | info | starting. Version 1.1.2 in C:/ioBroker/node_modules/iobroker.meross, node: v10.16.0

`

**Comment by Apollon77** [comment]
Please try Github version. But this can happen when devices are not reachable

**Comment by Apollon77** [comment]
It should try to reconnect or not in your case?

**Comment by Moormerlander** [comment]
Since I had no Meross devices yet I ordered a set of 4 pcs at Amazon today. I installed the latest version of the adapter from Github and I hope to get up and running. Will see next week if it works or not.

**Comment by Apollon77** [comment]
Please reopen if still problematic
