### ISSUE TITLE
MSL120 nicht bedienbar

### ISSUE THREAD

**Issue by danielmg112** [Apollon77/ioBroker.meross#21]
Hi,

ich habe die MSL120 und unter der 1.0.0 konnte ich zumindest an und aus schalten.
Seit der 1.1.2 funktioniert das nicht mehr und der Adapter kommt auch nicht mehr auf grün.
Folgende Fehlermeldung wird dann im Log angezeigt.

host.ioBroker-RasPi | 2019-08-27 18:31:19.722 | info | Restart adapter system.adapter.meross.0 because enabled
-- | -- | -- | --
host.ioBroker-RasPi | 2019-08-27 18:31:19.721 | error | instance system.adapter.meross.0 terminated with code 6 (uncaught exception)
host.ioBroker-RasPi | 2019-08-27 18:31:19.721 | error | Caught by controller[0]: at doWrite (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
host.ioBroker-RasPi | 2019-08-27 18:31:19.720 | error | Caught by controller[0]: at Writable.writable._write (/opt/iobroker/node_modules/mqtt/lib/client.js:294:5)
host.ioBroker-RasPi | 2019-08-27 18:31:19.720 | error | Caught by controller[0]: at work (/opt/iobroker/node_modules/mqtt/lib/client.js:283:12)
host.ioBroker-RasPi | 2019-08-27 18:31:19.720 | error | Caught by controller[0]: at MqttClient._handlePacket (/opt/iobroker/node_modules/mqtt/lib/client.js:351:12)
host.ioBroker-RasPi | 2019-08-27 18:31:19.719 | error | Caught by controller[0]: at MqttClient._handlePublish (/opt/iobroker/node_modules/mqtt/lib/client.js:1162:12)
host.ioBroker-RasPi | 2019-08-27 18:31:19.719 | error | Caught by controller[0]: at MqttClient.emit (events.js:217:7)
host.ioBroker-RasPi | 2019-08-27 18:31:19.718 | error | Caught by controller[0]: at emitThree (events.js:136:13)
host.ioBroker-RasPi | 2019-08-27 18:31:19.718 | error | Caught by controller[0]: at MqttClient.client.on (/opt/iobroker/node_modules/meross-cloud/index.js:239:66)
host.ioBroker-RasPi | 2019-08-27 18:31:19.717 | error | Caught by controller[0]: at Object.device.getSystemAllData [as callback] (/opt/iobroker/node_modules/iobroker.meross/main.js:396:17)
host.ioBroker-RasPi | 2019-08-27 18:31:19.717 | error | Caught by controller[0]: at initDeviceObjects (/opt/iobroker/node_modules/iobroker.meross/main.js:304:27)
host.ioBroker-RasPi | 2019-08-27 18:31:19.716 | error | Caught by controller[0]: ReferenceError: val is not defined
meross.0 | 2019-08-27 18:31:18.676 | debug | connected set to false
meross.0 | 2019-08-27 18:31:18.675 | debug | connected set to false
meross.0 | 2019-08-27 18:31:18.674 | debug | connected set to false
meross.0 | 2019-08-27 18:31:18.669 | info | Device: 1812147137869029088434298f19810f closed: null
meross.0 | 2019-08-27 18:31:18.668 | info | Device: 1812011278931829087334298f1894ae closed: null
meross.0 | 2019-08-27 18:31:18.667 | warn | Exception: ReferenceError: val is not defined
meross.0 | 2019-08-27 18:31:18.667 | error | ReferenceError: val is not defined at initDeviceObjects (/opt/iobroker/node_modules/iobroker.meross/main.js:304:27) at Object.device.getSystemAllData [as callback] (/opt/iobroker/node_modules/
meross.0 | 2019-08-27 18:31:18.666 | error | uncaught exception: val is not defined
meross.0 | 2019-08-27 18:31:18.665 | debug | 1812147137869029088434298f19810f: initDeviceObjects with channels = [{}] and data = {"togglex":[{"channel":0,"onoff":0,"lmTime":1566923303}],"triggerx":[],"timerx":[],"light":{"capacity":6,"channel":0
meross.0 | 2019-08-27 18:31:18.664 | debug | 1812147137869029088434298f19810f All-Data: {"all":{"system":{"hardware":{"type":"msl120","subType":"us","version":"2.0.0","chipType":"mt7682","uuid":"1812147137869029088434298f19810f","macAddress":"34
meross.0 | 2019-08-27 18:31:18.430 | debug | Device Raw: 1812011278931829087334298f1894ae - data: {"header":{"messageId":"a140f1e2f1da66d1eccd8083acc6bce2","namespace":"Appliance.System.Ability","method":"GETACK","payloadVersion":1,"from":"/appl
meross.0 | 2019-08-27 18:31:18.430 | debug | Device Send Raw: 1812011278931829087334298f1894ae - data: {"header":{"from":"/app/222050-61bd821bb49039165a484a55f74cac9c/subscribe","messageId":"30746ed02ec6416ed691e23a2d8be8c1","method":"GET","name
meross.0 | 2019-08-27 18:31:18.429 | debug | 1812011278931829087334298f1894ae Abilities: {"payloadVersion":1,"ability":{"Appliance.Config.Key":{},"Appliance.Config.WifiList":{},"Appliance.Config.Wifi":{},"Appliance.Config.Trace":{},"Appliance.Sy
meross.0 | 2019-08-27 18:31:18.399 | debug | Device Raw: 1812147137869029088434298f19810f - data: {"header":{"messageId":"c02ebd28629cee2188bafde7b105370f","namespace":"Appliance.System.Ability","method":"GETACK","payloadVersion":1,"from":"/appl
meross.0 | 2019-08-27 18:31:18.397 | debug | Device Send Raw: 1812147137869029088434298f19810f - data: {"header":{"from":"/app/222050-ac991d0d4736287578bacd666b936f04/subscribe","messageId":"bb9afb18d5c455c9f5eb584c1d42cd73","method":"GET","name
meross.0 | 2019-08-27 18:31:18.396 | debug | 1812147137869029088434298f19810f Abilities: {"payloadVersion":1,"ability":{"Appliance.Config.Key":{},"Appliance.Config.WifiList":{},"Appliance.Config.Wifi":{},"Appliance.Config.Trace":{},"Appliance.Sy
meross.0 | 2019-08-27 18:31:18.276 | debug | Device Send Raw: 1812147137869029088434298f19810f - data: {"header":{"from":"/app/222050-ac991d0d4736287578bacd666b936f04/subscribe","messageId":"c02ebd28629cee2188bafde7b105370f","method":"GET","name
meross.0 | 2019-08-27 18:31:18.275 | info | Device: 1812147137869029088434298f19810f connected
meross.0 | 2019-08-27 18:31:18.215 | debug | connected set to true
meross.0 | 2019-08-27 18:31:18.211 | debug | Device Send Raw: 1812011278931829087334298f1894ae - data: {"header":{"from":"/app/222050-61bd821bb49039165a484a55f74cac9c/subscribe","messageId":"a140f1e2f1da66d1eccd8083acc6bce2","method":"GET","name
meross.0 | 2019-08-27 18:31:18.209 | info | Device: 1812011278931829087334298f1894ae connected
meross.0 | 2019-08-27 18:31:17.854 | debug | {"uuid":"1812011278931829087334298f1894ae","onlineStatus":1,"devName":"Schlafzimmer Licht","devIconId":"device028_eu","bindTime":1557343421,"deviceType":"mss510h","subType":"eu","channels":[{}],"regio
meross.0 | 2019-08-27 18:31:17.847 | info | Device 1812011278931829087334298f1894ae initialized
meross.0 | 2019-08-27 18:31:17.843 | debug | {"uuid":"1812147137869029088434298f19810f","onlineStatus":1,"devName":"Büro Lampe","devIconId":"device036","bindTime":1566835294,"deviceType":"msl120","subType":"eu","channels":[{}],"region":"eu","fmw
meross.0 | 2019-08-27 18:31:17.842 | info | Device 1812147137869029088434298f19810f initialized
meross.0 | 2019-08-27 18:31:16.771 | debug | connected set to false
meross.0 | 2019-08-27 18:31:16.653 | info | starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.meross, node: v8.15.0
host.ioBroker-RasPi | 2019-08-27 18:31:12.198 | info | instance system.adapter.meross.0 started with pid 24240
host.ioBroker-RasPi | 2019-08-27 18:31:12.171 | info | object change system.adapter.meross.0
host.ioBroker-RasPi | 2019-08-27 18:31:01.204 | info | instance system.adapter.meross.0 terminated with code 3 (Adapter disabled or invalid config)
meross.0 | 2019-08-27 18:31:01.141 | error | adapter disabled
meross.0 | 2019-08-27 18:31:01.023 | info | States connected to redis: 127.0.0.1:6379
meross.0 | 2019-08-27 18:31:01.009 | debug | statesDB connected
meross.0 | 2019-08-27 18:31:00.935 | debug | objectDB connected
host.ioBroker-RasPi | 2019-08-27 18:30:59.364 | info | stopInstance system.adapter.meross.0 killing pid 23763
host.ioBroker-RasPi | 2019-08-27 18:30:59.363 | info | stopInstance system.adapter.meross.0
host.ioBroker-RasPi | 2019-08-27 18:30:59.362 | info | "system.adapter.meross.0" disabled
host.ioBroker-RasPi | 2019-08-27 18:30:59.359 | info | object change system.adapter.meross.0
host.ioBroker-RasPi | 2019-08-27 18:30:56.717 | info | instance system.adapter.meross.0 started with pid 23763
host.ioBroker-RasPi | 2019-08-27 18:30:56.685 | info | object change system.adapter.meross.0
host.ioBroker-RasPi | 2019-08-27 18:30:37.893 | info | Restart adapter system.adapter.meross.0 because enabled

**Comment by Apollon77** [comment]
Kannst Du bitte Log nochmal ziehen, abert NICHT aus dem Admin kopieren sondern aus dem Logfile (ioBroker-verzeichnis dort Unterverzeichnis log). Admin schneidet leider Zeilen ab :-(

**Comment by Apollon77** [comment]
Bzw versuch mal folgendes:

Editiere mal die Datei /opt/iobroker/node_modules/iobroker.meross/main,js in Zeile 304

von:

```
            common.name = val.channel + '-' + key;
```

nach 

```
            common.name = data.light.channel + '-' + key;
```

Geht es danach?

**Comment by Apollon77** [comment]
please try 1.2.0 from github
