### ISSUE TITLE
Monatsverbrauch?

### ISSUE THREAD

**Issue by tommyMX** [Apollon77/ioBroker.meross#211]
Hallo,

Wäre es möglich Daten wie Tagesverbrauch, Monatsverbrauch und Gesamtverbrauch in kWh zu implementieren?

VG

**Comment by Apollon77** [comment]
duplicate #85 korrekt?

**Comment by tommyMX** [comment]
> duplicate #85 korrekt?

yes

any updates on this?

The post is from march....

**Comment by Apollon77** [comment]
Yes and I had no time since march to take a look at this ... sorry for that, check my other activities and you know why
