### ISSUE TITLE
Temperature warning

### ISSUE THREAD

**Issue by Erbse69** [Apollon77/ioBroker.meross#212]
My 3 Shelly dimmers fill up my iobroker log with warnings due to over temperature, like this one:
shelly.0
2021-08-31 22:18:13.770	warn	State value to set for "shelly.0.SHDM-2#xxxxxxxxxxxxxxx#1.temperatureF" has value "122.7" greater than max "100"
I'm not sure where this limit of 100° Fahrenheit comes from and I'm also wondering about this, because this is only a temperature of approx 38° Celsius. It's there maybe an error and this limit should be 100° Celsius?

**Comment by Apollon77** [comment]
Then please check the issues in the shelly repository ... this is meross

**Comment by Erbse69** [comment]
Uuups, sorry!
