### ISSUE TITLE
Meross Jalousiesteuerung

### ISSUE THREAD

**Issue by BastianQuathamer** [Apollon77/ioBroker.meross#225]
Hallo zusammen, 
leider ist es nicht möglich über den Meross Adapter die Jalousiesteuerung zu bedienen. 
Es gibt keine Datenpunkte für hoch/herunter/Pause. Es gibt nur den Datenpunkt "online". Kann man dies eventuell hinzufügen oder Gibt es eine andere Möglichkeit?

![meross](https://user-images.githubusercontent.com/93195805/138867485-120625a2-04c0-4ebb-9077-b6f15d4b2149.png)
![meross2](https://user-images.githubusercontent.com/93195805/138867488-b7ac8ca4-fc12-41e1-8781-6989955f2b2a.png)

**Comment by Apollon77** [comment]
danke, habe denke morgen was zum testen

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by Apollon77** [comment]
Please provide a new log in any case of some actions

**Comment by Apollon77** [comment]
1.7.0
