### ISSUE TITLE
MEROSS services down?

### ISSUE THREAD

**Issue by Moormerlander** [Apollon77/ioBroker.meross#231]
Seit heute funktioniert die Meross-Instanz nicht mehr, Auszug aus dem Log:

meross.0
2021-11-03 08:55:43.015 info Device: 19062003897945251h0748e1e90044aa error: Error: Connection refused: Server unavailable

meross.0
2021-11-03 08:55:43.013 info Device: 19062099169505251h0748e1e900405a error: Error: Connection refused: Server unavailable

Any idea?

**Comment by ericiesw** [comment]
hallo
funktioniert in der Meross App auch nicht

**Comment by Moormerlander** [comment]
Hier ist die Erklärung:

A scheduled cloud service maintenance will be from 1:00am Nov 3rd to 2:00pm Nov 4th, Greenwich time. We will upgrade cloud service for Europe region. If you find your Meross devices not performing as expected or third-party voice assistant not responding, please upgrade both meross app and device firmware to the latest version and retry after 2:00pm Nov 4th. Please don't reset them.

Das haben die zwischenzeitlich auf der Webseite veröffentlicht

**Comment by Apollon77** [comment]
Thank you!
