### ISSUE TITLE
Meross MTS150 Heizkör

### ISSUE THREAD

**Issue by Escolate76** [Apollon77/ioBroker.meross#232]
Hi
habe mir Meross Heizkörpertermostate MTS 150 zugelegt und bekomme als Datenpunkte im ioBroker leider nur online und switch, dabei stehen beide immer auf true

![image](https://user-images.githubusercontent.com/92606136/140654975-d0d60ec6-bff7-4a80-a3ab-a822f61b9e25.png)

hier hätte ich natürlich liebend gerne die entsprechenden Datenpunkte.

ich habe folgende Aktionen ausgeführt

Auf der Meross App am Handy
17.04 Button manuell gestellt
17.04 Button 27.0 C aufwärmen gedrück
17.05 Button 21.0 C abkühlen gedrück
17.06 Button 15.0 C Economy gedrück
17.07 auf 18.0 C gedreht
17.07 auf 26.0 C gedreht
17.08 Ein/Aus Button gedrück -auf Aus
17.09 Ein/Aus Button gedrück -auf An
17.09 Button Automatisch gedrückt
Am Gerät selber
17.10 auf 24.0 C gestellt
17.11 auf 22.0 C gestellt
17.11 Aus gestellt
per Meross App
17.12 Button Ein gedrückt
Auf der Meross App am Handy
17.26 Button Automatisch gedrückt
17.28 Button manuell gestellt
17.31 Button 27.0 C aufwärmen gedrück
17.33 Button 21.0 C abkühlen gedrück
17.35 Button 15.0 C Economy gedrück
17.37 auf 18.0 C gedreht
17.39 auf 26.0 C gedreht
17.41 Ein/Aus Button gedrück -auf Aus
17.43 Ein/Aus Button gedrück -auf An
17.45 Button Automatisch gedrückt
Am Gerät selber
17.47 auf 24.0 C gestellt
17.49 auf 22.0 C gestellt
17.51 Aus gestellt
per Meross App
17.53 Button Ein gedrückt auf Aus
17.53 Button Ein gedrückt auf An

ich hoffe daraus kann man etwas machen.

ich bedanke mich schon mal im vorraus für die Bemühungen.

Lieben Gruß

**Versions:**  
 - Adapter version: <meross 1.6.3>
 - JS-Controller version: <js-controller: 3.3.18> 
 - Node version: <node: v16.13.0> 
 - Operating system: <ioBroker>

**Additional context**  
Add any other context about the problem here
[iobroker.2021-11-07.log](https://github.com/Apollon77/ioBroker.meross/files/7492729/iobroker.2021-11-07.log)
.

**Comment by Apollon77** [comment]
Danke.checke es die Tage

**Comment by Apollon77** [comment]
Das Log ist gut, aber es fehlt der Debug Teil vom Adapterstart ... war wohl einen Tag vorher :-) haste Du das bitte noch?

**Comment by Apollon77** [comment]
Ok, Habe log von anderen ... mache hier zu, weiter in #224

**Comment by Apollon77** [comment]
@Escolate76 DANKE!!
