### ISSUE TITLE
Farbtemperatur der Smarte LED Nachttischlampe

### ISSUE THREAD

**Issue by lindi200000** [Apollon77/ioBroker.meross#233]
Hallo,
Ich habe folgende Nachttischlampe gekauft: https://www.amazon.de/gp/product/B089SKRBQW
der Adapter erkennt sie super, jedoch hab ich Probleme mit der Farbtemperatur (besonders bei Weis).
Ich hab die Lampe über den IOT Adapter angebunden. Wenn ich hier sage "schalte auf kaltweis" dann wird 7000k gesetzt.
Wenn ich über die Meross App Kaltweis einstelle, dann wird im DP meross.0.xxxxxxx.0-temperature 100 angezeigt.

nach hin und her testen darf der Datenpunkt nur zwischen 0 und 100 liegen. Lässt sich hier was machen, das man mit dem normalen Farbtemperaturen arbeiten kann?

Installiert ist der Adapter in der Version 1.6.3 (stable).

VG

**Comment by Apollon77** [comment]
Na dann würde ich sagen: Bitte ermittle alle relevanten Farbtemperatiuren aus der Meross app ... also per App setzen, aufschreiben was der Wert sagt.

Laut Anleitung soll es der Bereich 2700~6500K  sein ... kannst ja mal schauen welche werte auch anders rum - also adapter gesetzt welche wirkung haben.

**Comment by lindi200000** [comment]
Von der App aus ist es kaum zu sagen. Da dreht man nur an einen Kreis. Werte ändern sich in iobroker von 0 bis 100.
Andersrum habe ich es im iot Adapter besser auswerten können. Die weiß Farben können natürlich dann nur geschätzt werden. Provisorisch läuft erstmal folgendes Script um die Werte zu übersetzen. 
![unknown](https://user-images.githubusercontent.com/16406425/142070014-162c5728-4931-4945-a107-4e5c6b59b392.png)

**Comment by Apollon77** [comment]
Das Problem ist an der Stelle das verschiedene Meross Devices ggf hier verschiedene Temperatur-Bereiche haben. Also wenn ich nachdenke würde ich da weniger im Adapter was tun.

Am besten legst Du Dir einen Alias Objekt für die Temperatur an, gibst dem dann min 2700 und max 6500 an und machst ne Umrechnugn von 0..100 auf diese Werte. bei der Nummer gibts bestimmt hilfe im Forum
