### ISSUE TITLE
MTS100 Heizkörperthermostat mit Hub MTS100H keine Datenpunkte verfügbar

### ISSUE THREAD

**Issue by goohnie** [Apollon77/ioBroker.meross#24]
Ich nutze Adapterversion 1.20, der Hub wird erkannt, aber kein Thermostat dazu.
Es wäre schön, wenn die Thermostate ansprechbar wären.

übernommen aus :
https://forum.iobroker.net/topic/23641/test-adapter-meross-v1-1-x/39

`
meross.0	2019-11-04 18:42:13.500	info	(27070) Devices initialized
--
  | meross.0	2019-11-04 18:42:13.500	debug	(27070) Device Send Raw: 19082963309123251h1248e1e900a721 - data: {"header":{"from":"/app/328853-9a3cfe5bcfe13f5865e95923072b0d64/subscribe","messageId":"fd3665b71ee8026d6721f857bf8ca0c1","method":"G
  | meross.0	2019-11-04 18:42:13.499	debug	(27070) Device Send Raw: 19082912831870251h1248e1e900a04e - data: {"header":{"from":"/app/328853-2398aa9c10b3ccc44462b78d40c88480/subscribe","messageId":"e8e94b7e91dbf16d5d562661b08285ad","method":"G
  | meross.0	2019-11-04 18:42:13.456	debug	(27070) Device Raw: 19082963309123251h1248e1e900a721 - data: {"header":{"messageId":"f70d491ec3841f53cd2f8b60d67f1ff6","namespace":"Appliance.Control.Electricity","method":"GETACK","payloadVersion":1
  | meross.0	2019-11-04 18:42:13.455	debug	(27070) 19082963309123251h1248e1e900a721: initDeviceObjects with channels = [{}] and data = {"electricity":{"channel":0,"current":0,"voltage":2274,"power":0,"config":{"voltageRatio":188,"electricityR
  | meross.0	2019-11-04 18:42:13.454	debug	(27070) 19082963309123251h1248e1e900a721 Electricity: {"electricity":{"channel":0,"current":0,"voltage":2274,"power":0,"config":{"voltageRatio":188,"electricityRatio":100}}}
  | meross.0	2019-11-04 18:42:13.452	debug	(27070) Device Raw: 19082912831870251h1248e1e900a04e - data: {"header":{"messageId":"98b9170ff987e8ce43b563158f1db20f","namespace":"Appliance.Control.Electricity","method":"GETACK","payloadVersion":1
  | meross.0	2019-11-04 18:42:13.450	debug	(27070) 19082912831870251h1248e1e900a04e: initDeviceObjects with channels = [{}] and data = {"electricity":{"channel":0,"current":0,"voltage":2237,"power":0,"config":{"voltageRatio":188,"electricityR
  | meross.0	2019-11-04 18:42:13.450	debug	(27070) 19082912831870251h1248e1e900a04e Electricity: {"electricity":{"channel":0,"current":0,"voltage":2237,"power":0,"config":{"voltageRatio":188,"electricityRatio":100}}}
  | meross.0	2019-11-04 18:42:11.971	debug	(27070) Device Raw: 19082912831870251h1248e1e900a04e - data: {"header":{"messageId":"1a95b3439b6d1295e15aaeae952d8318","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"
  | meross.0	2019-11-04 18:42:11.971	debug	(27070) 19082912831870251h1248e1e900a04e Electricity scheduled in : 20s
  | meross.0	2019-11-04 18:42:11.970	debug	(27070) Device Send Raw: 19082912831870251h1248e1e900a04e - data: {"header":{"from":"/app/328853-2398aa9c10b3ccc44462b78d40c88480/subscribe","messageId":"98b9170ff987e8ce43b563158f1db20f","method":"G
  | meross.0	2019-11-04 18:42:11.969	debug	(27070) 19082912831870251h1248e1e900a04e: initDeviceObjects with channels = [{}] and data = {"togglex":[{"channel":0,"onoff":0,"lmTime":1572709018}],"triggerx":[],"timerx":[]}
  | meross.0	2019-11-04 18:42:11.968	debug	(27070) 19082912831870251h1248e1e900a04e All-Data: {"all":{"system":{"hardware":{"type":"mss310","subType":"un","version":"2.0.0","chipType":"mt7682","uuid":"19082912831870251h1248e1e900a04e","macAdd
  | meross.0	2019-11-04 18:42:11.933	debug	(27070) Device Raw: 19082963309123251h1248e1e900a721 - data: {"header":{"messageId":"79854c7814f996da93058bcc1ffe4001","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"
  | meross.0	2019-11-04 18:42:11.932	debug	(27070) 19082963309123251h1248e1e900a721 Electricity scheduled in : 20s
  | meross.0	2019-11-04 18:42:11.932	debug	(27070) Device Send Raw: 19082963309123251h1248e1e900a721 - data: {"header":{"from":"/app/328853-9a3cfe5bcfe13f5865e95923072b0d64/subscribe","messageId":"f70d491ec3841f53cd2f8b60d67f1ff6","method":"G
  | meross.0	2019-11-04 18:42:11.929	debug	(27070) 19082963309123251h1248e1e900a721: initDeviceObjects with channels = [{}] and data = {"togglex":[{"channel":0,"onoff":0,"lmTime":1572028129}],"triggerx":[],"timerx":[]}
  | meross.0	2019-11-04 18:42:11.928	debug	(27070) 19082963309123251h1248e1e900a721 All-Data: {"all":{"system":{"hardware":{"type":"mss310","subType":"un","version":"2.0.0","chipType":"mt7682","uuid":"19082963309123251h1248e1e900a721","macAdd
  | meross.0	2019-11-04 18:42:11.926	debug	(27070) Device Raw: 1811069847989629086034298f17d056 - data: {"header":{"messageId":"b06e95236ee26370b34e476023bd832a","namespace":"Appliance.System.Online","method":"GETACK","payloadVersion":1,"from
  | meross.0	2019-11-04 18:42:11.925	debug	(27070) Online: {"online":{"status":1}}
  | meross.0	2019-11-04 18:42:11.827	debug	(27070) Device Send Raw: 1811069847989629086034298f17d056 - data: {"header":{"from":"/app/328853-f51ad779afcbe07a29af06bb1834ca04/subscribe","messageId":"b06e95236ee26370b34e476023bd832a","method":"G
  | meross.0	2019-11-04 18:42:11.756	debug	(27070) Device Raw: 1811069847989629086034298f17d056 - data: {"header":{"messageId":"315371004881461212ea7cf7dc752658","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"
  | meross.0	2019-11-04 18:42:11.752	debug	(27070) 1811069847989629086034298f17d056: initDeviceObjects with channels = [{}] and data = {"hub":{"hubId":53334,"mode":0,"subdevice":[{"id":"0100224E","status":1,"onoff":1,"lastActiveTime":15728893
  | meross.0	2019-11-04 18:42:11.748	debug	(27070) 1811069847989629086034298f17d056 All-Data: {"all":{"system":{"hardware":{"type":"msh300","subType":"un","version":"2.0.0","chipType":"mt7682","uuid":"1811069847989629086034298f17d056","macAdd
  | meross.0	2019-11-04 18:42:11.613	debug	(27070) Device Raw: 19082912831870251h1248e1e900a04e - data: {"header":{"messageId":"b0d43f4f2ee92fa227ab22ef87531d3c","namespace":"Appliance.System.Ability","method":"GETACK","payloadVersion":1,"fro
  | meross.0	2019-11-04 18:42:11.612	debug	(27070) Device Send Raw: 19082912831870251h1248e1e900a04e - data: {"header":{"from":"/app/328853-2398aa9c10b3ccc44462b78d40c88480/subscribe","messageId":"1a95b3439b6d1295e15aaeae952d8318","method":"G
  | meross.0	2019-11-04 18:42:11.611	debug	(27070) 19082912831870251h1248e1e900a04e Abilities: {"payloadVersion":1,"ability":{"Appliance.Config.Key":{},"Appliance.Config.WifiList":{},"Appliance.Config.Wifi":{},"Appliance.Config.Trace":{},"App
  | meross.0	2019-11-04 18:42:11.610	debug	(27070) Device Raw: 19082963309123251h1248e1e900a721 - data: {"header":{"messageId":"16effd4dca1083631559d2761e079fff","namespace":"Appliance.System.Ability","method":"GETACK","payloadVersion":1,"fro
  | meross.0	2019-11-04 18:42:11.610	debug	(27070) Device Send Raw: 19082963309123251h1248e1e900a721 - data: {"header":{"from":"/app/328853-9a3cfe5bcfe13f5865e95923072b0d64/subscribe","messageId":"79854c7814f996da93058bcc1ffe4001","method":"G
  | meross.0	2019-11-04 18:42:11.609	debug	(27070) 19082963309123251h1248e1e900a721 Abilities: {"payloadVersion":1,"ability":{"Appliance.Config.Key":{},"Appliance.Config.WifiList":{},"Appliance.Config.Wifi":{},"Appliance.Config.Trace":{},"App
  | meross.0	2019-11-04 18:42:11.542	debug	(27070) Device Raw: 1811069847989629086034298f17d056 - data: {"header":{"messageId":"16d390cd3d4ecdb15f7e3f78c86cbc31","namespace":"Appliance.System.Ability","method":"GETACK","payloadVersion":1,"fro
  | meross.0	2019-11-04 18:42:11.542	debug	(27070) Device Send Raw: 1811069847989629086034298f17d056 - data: {"header":{"from":"/app/328853-f51ad779afcbe07a29af06bb1834ca04/subscribe","messageId":"315371004881461212ea7cf7dc752658","method":"G
  | meross.0	2019-11-04 18:42:11.540	debug	(27070) 1811069847989629086034298f17d056 Abilities: {"payloadVersion":1,"ability":{"Appliance.Config.Key":{},"Appliance.Config.WifiList":{},"Appliance.Config.Wifi":{},"Appliance.Config.Trace":{},"App
  | meross.0	2019-11-04 18:42:11.348	debug	(27070) connected set to true
  | meross.0	2019-11-04 18:42:11.345	debug	(27070) Device Send Raw: 19082912831870251h1248e1e900a04e - data: {"header":{"from":"/app/328853-2398aa9c10b3ccc44462b78d40c88480/subscribe","messageId":"b0d43f4f2ee92fa227ab22ef87531d3c","method":"G
  | meross.0	2019-11-04 18:42:11.344	info	(27070) Device: 19082912831870251h1248e1e900a04e connected
  | meross.0	2019-11-04 18:42:11.342	debug	(27070) Device Send Raw: 19082963309123251h1248e1e900a721 - data: {"header":{"from":"/app/328853-9a3cfe5bcfe13f5865e95923072b0d64/subscribe","messageId":"16effd4dca1083631559d2761e079fff","method":"G
  | meross.0	2019-11-04 18:42:11.341	info	(27070) Device: 19082963309123251h1248e1e900a721 connected
  | meross.0	2019-11-04 18:42:11.336	debug	(27070) Device Send Raw: 1811069847989629086034298f17d056 - data: {"header":{"from":"/app/328853-f51ad779afcbe07a29af06bb1834ca04/subscribe","messageId":"16d390cd3d4ecdb15f7e3f78c86cbc31","method":"G
  | meross.0	2019-11-04 18:42:11.332	info	(27070) Device: 1811069847989629086034298f17d056 connected
  | meross.0	2019-11-04 18:42:11.141	debug	(27070) {"uuid":"19082912831870251h1248e1e900a04e","onlineStatus":1,"devName":"Sidewinder","devIconId":"device024","bindTime":1569591975,"deviceType":"mss310","subType":"eu","channels":[{}],"region":
  | meross.0	2019-11-04 18:42:11.141	info	(27070) Device 19082912831870251h1248e1e900a04e initialized
  | meross.0	2019-11-04 18:42:11.139	debug	(27070) {"uuid":"19082963309123251h1248e1e900a721","onlineStatus":1,"devName":"Ender","devIconId":"device024","bindTime":1569592704,"deviceType":"mss310","subType":"eu","channels":[{}],"region":"eu",
  | meross.0	2019-11-04 18:42:11.139	info	(27070) Device 19082963309123251h1248e1e900a721 initialized
  | meross.0	2019-11-04 18:42:11.070	debug	(27070) {"uuid":"1811069847989629086034298f17d056","onlineStatus":1,"devName":"Smart Hub","devIconId":"device024","bindTime":1570464512,"deviceType":"msh300","subType":"un","channels":[{}],"region":"
  | meross.0	2019-11-04 18:42:11.069	info	(27070) Device 1811069847989629086034298f17d056 initialized
  | meross.0	2019-11-04 18:42:10.616	debug	(27070) connected set to false
  | meross.0	2019-11-04 18:42:10.574	debug	(27070) States connected to redis: 0.0.0.0:9000
  | meross.0	2019-11-04 18:42:10.560	info	(27070) starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.meross, node: v10.17.0
  | meross.0	2019-11-04 18:42:10.490	debug	(27070) statesDB connected
  | meross.0	2019-11-04 18:42:10.486	debug	(27070) Objects connected to redis: 0.0.0.0:9001
  | meross.0	2019-11-04 18:42:10.485	debug	(27070) Redis States: Use Redis connection: 0.0.0.0:9000
  | meross.0	2019-11-04 18:42:10.483	debug	(27070) objectDB connected
  | meross.0	2019-11-04 18:42:10.244	debug	(27070) Redis Objects: Use Redis connection: 0.0.0.0:9001
  | {1}
`

**Comment by Apollon77** [comment]
Bitte nochmals Debug Log posten, diesmal vollständig aus dem Logfile und NICHT aus dem Admin kopiert (wird abgeschnitten)

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/26953/test-meross-adapter-1-2-x Please test and provide Feedback

**Comment by Apollon77** [comment]
1.2.2 bitte testen! (und das ist das issue für Thermostat) :-))
