### ISSUE TITLE
MSS210RTL irgendwann offline

### ISSUE THREAD

**Issue by URI3L-23** [Apollon77/ioBroker.meross#240]
Ich benutze 9 Steckdosen des Typs "mss210rtl". Diese werden über die Instanz gefunden und lassen sich auch problemlos bedienen. Allerdings werden die Steckdosen nach einer Zeit als offline angezeigt - lassen sich aber trotzdem noch über iobroker bedienen. Der Status "online" wird nur durch Neustart der Instanz erreicht.
Die Steckdosen sind nicht dauerhaft in Betrieb (z.B. als Weihnachtsbeleuchtung). Um unnötige Fehlermeldungen zu produzieren,  frage ich deshalb in der Blockly-Funktion den online-status ab bevor diese geschalten werden.
Der Zeitpunkt bzw. die Ursache, warum diese offline gehen ist nicht nachvollziebar. In der Meross-App bleiben die Steckdosen allerdings online.

**Versions:**  
 - Adapter version: 1.6.3
 - JS-Controller version: 3.3.22
 - Node version: 12.22.1
 - Operating system: Raspbian 10 Buster

btw: Bei Installation einer Instanz wird das Config-Fenster geöffnet (Username, Password, Polling-Intervall) und lässt sich ausfüllen. Bei erneutem öffnen des Config-Fensters werden die  Einträge nicht mehr angezeigt und lassen sich auch nicht mehr ändern.

Gruß
Heiko

**Comment by Apollon77** [comment]
Dann bitte mal Loglebel der Meross Instanz auf Debug stellen (Admin - Instanzen - Expertenmodus - Instanz aufklappen und Loglevel von Info -> Debug stellen) und dann Log posten von "da wo es offline geht" (plus bissl davor und danach)

**Comment by URI3L-23** [comment]
> Dann bitte mal Loglebel der Meross Instanz auf Debug stellen (Admin - Instanzen - Expertenmodus - Instanz aufklappen und Loglevel von Info -> Debug stellen) und dann Log posten von "da wo es offline geht" (plus bissl davor und danach)

ok. Loglevel ist eingerichtet. Ich poste die Logeinträge, sobald die Devices offline gehen. 
Vielen Dank
(und frohe Weihnachten :)

**Comment by URI3L-23** [comment]
Hallo,

ich habe den Admin-Adapter auf Version 5.2.3 hochgezogen und seitdem bleiben (zumindest bis jetzt) die Steckdosen online. Hatte aber vorher alle paar Tage diese offline Problematik. Ich würde es jetzt noch ein paar Tage weiterhin beobachten und werde dann den issue schließen.

Gruß
Heiko

**Comment by Apollon77** [comment]
Hi,

strange... keine AHnung wie Admin da irgendwas mit zu tun haben kann :-)) aber ok ... Dann mach ich hier zu und du wieder auf falls relevant, ok?

**Comment by URI3L-23** [comment]
> Hi,
> 
> strange... keine AHnung wie Admin da irgendwas mit zu tun haben kann :-)) aber ok ... Dann mach ich hier zu und du wieder auf falls relevant, ok?

ok. Sorry, dass ich ein issue aufgemacht habe. Aber das Problem war wirklich vorhanden. Ich hatte auch mal eine zweite Instanz erstellt und dort war es auch vorhanden. Sehr suspekt...

**Comment by Apollon77** [comment]
Du hast mich falsch verstanden!! Issues sind genau richtig. Kein grund für ein sorry!
