### ISSUE TITLE
On V1.8.0 since a week many warnings in the log " Can not get Abilities for Device "

### ISSUE THREAD

**Issue by Saarblick** [Apollon77/ioBroker.meross#248]
But functionality is given!

Here some lines from the logs:

meross.0 | Zeit | info | Nachricht
-- | -- | -- | --
meross.0 | 2022-01-27 19:29:42.543 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:29:36.655 | warn | State "meross.0.0-garageDoorWorking" has no existing object, this might lead to an error in future versions
meross.0 | 2022-01-27 19:29:19.813 | warn | State "meross.0.0-garageDoorWorking" has no existing object, this might lead to an error in future versions
meross.0 | 2022-01-27 19:28:22.541 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:27:02.539 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:25:42.535 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:24:22.533 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:23:02.529 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:21:42.526 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:20:22.523 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:19:02.519 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:17:42.515 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:16:22.513 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:15:02.512 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:13:42.509 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:12:22.507 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:11:02.506 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:09:42.503 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:08:22.501 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:07:02.498 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:05:42.495 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined
meross.0 | 2022-01-27 19:04:22.492 | warn | Can not get Abilities for Device 2007162402138490819648e1e9254259: Error: Timeout / undefined

</div></div>
</body>
</html>

**Comment by Apollon77** [comment]
Please provide a full debug log from the adapter (Admin - enable expert mode - Instances - expand the meross instanece - change loglevel to debug) and then get log from logfile on disk at /opt/iobroer/logs/...

I need log from adapterstart and untill the error appears.

Normally this error happens when the device is not responding to the cloud ... so it could be that the "Local contro"L works but cloud still gets that error ... so I need to check that please

**Comment by Apollon77** [comment]
PS: Please send log as email to iobroker@fischer-ka.de and reference this github issue
