### ISSUE TITLE
Meross Garagenöffner

### ISSUE THREAD

**Issue by ChristianHohman** [Apollon77/ioBroker.meross#265]
Hey gibt es eine Möglichkeit auch den Öffnungsstand vom magnetsensor vom Garagentoröffner abzufragen?

Liebe Grüße 
Danke für deine Arbeit

**Comment by Apollon77** [comment]
Bisher ist nach aktuellem Wissen alles Implementiert ... sonst gern debug log erstellen und sagen wann sich zeitlich der megnetsensor Status geändert haben müsste ...dann kann ich schauen. Aber ich glaube da ging nix weiter

**Comment by ChristianHohman** [comment]
also bei mir wird er einfach gar nicht aufgeführt.
<img width="1137" alt="Bildschirmfoto 2022-03-26 um 21 53 23" src="https://user-images.githubusercontent.com/65295025/160256771-c1d3772c-738d-4fd4-b98e-fc6d2bdbfcc2.png">

**Comment by Apollon77** [comment]
Daher sprach ich vom Debug log ... meine erinnerung sagt mir das der magnetkontakt nicht extra exposed ist sondern vom gerät nur genutzt wird um zu erkennen was der status ist

**Comment by Frazor12** [comment]
Ich vermute mal er braucht das fürs Einbinden in yakha. 
Gibts da eine Möglichkeit?

**Comment by ChristianHohman** [comment]
es gibt wohl verschiedene Versionen von dem meross; meine ist auch ohne HomeKit Unterstützung.
Ich habe das ding jetzt rausgeschmissen! Meine Lösung: 1 ESP, der schaltet und 2 Magnetsensoren abfragt. fertig.

**Comment by Frazor12** [comment]
Ja meiner auch, jedoch hätte ich trotzdem gehofft das ich in via iobroker ins homekit bekomme. 
dem scheint nicht so... 
deine lösung ist nicht schlecht, welche kontakte hast du dazu verwendet?

**Comment by Apollon77** [comment]
naja Ihr bekommt es schon rein, aber halt ohne den Öffnungsstand weil es den halt leider von Meross als Status nicht gibt

**Comment by ChristianHohman** [comment]
In der App schon!

**Comment by Apollon77** [comment]
Und das stimmt auch wenn du es per ioBroker fährst und mittendrin stoppst oder so? Meines Wissens nach macht die app genau das gleiche wie ioBroker ... "sie errät den Status". Weil sonst wäre es in den Daten drin

**Comment by Frazor12** [comment]
@ChristianHohman wie hast du den ESP in den iobroker eingebunden? Sprich welchen Adapter hast du verwendet?

**Comment by ChristianHohman** [comment]
Tasmota auf esp und dann mit dem sonoff Adapter
