### ISSUE TITLE
0-garageDoorWorking Objekt bleibt auf false

### ISSUE THREAD

**Issue by sdGigatec** [Apollon77/ioBroker.meross#270]
Hey Apollon77, 

setze die aktuelle Version 1.10.4 Deines Meross Cloud Adapters ein und habe zwei msg100 Toröffner im Einsatz. Funktioniert ausgezeichnet, vielen Dank für Deine Arbeit!

Leider ändert sich das Objekt 0-garageDoorWorking nicht auf true während das Tor verfährt. Ist das ein bekannter Fehler, eine Einschränkung der Hardware oder habe ich was verballert?

Debug Log eines ab Start des Adapters inkl. einer Öffnung und einer Schließung schicke ich Dir gleich per Mail (mit Referenz auf dieses Issue). 

Freue ich mich auf eine kurz Rückmeldung, Grüße Markus

**Comment by Apollon77** [comment]
0-garageDoorWorking funktioniert nur wenn die Aktion über iobroker gestartet wurde, weil dann klar ist das was passiert. Wenn die Aktion per App oder Schalter gestartet wurde kann der Adapter das leider nicht ermitteln.

Kann es das sein?

**Comment by Apollon77** [comment]
In den Meross Daten ist das nicht sauber ersichtlich, sorry
