### ISSUE TITLE
Meross Connection Error: Error: 0: 

### ISSUE THREAD

**Issue by MyzerAT** [Apollon77/ioBroker.meross#271]
**Describe the bug**  

Meross Instanz startet mit Fehler:
**meross.0	2022-04-14 16:37:54.124	error	Meross Connection Error: Error: 0:** 

**Versions:**  
 - Adapter version: 1.10.1
 - JS-Controller version: 4.0.21
 - Node version: 12.22.1
 - Operating system: Master Debian 10.10.0 (Wien)
Intel NUC6CAYH 8GB RAM, 240 GB SSD & Proxmox

![1649946595797-44da81c7-9620-419b-a6a5-1a35a6527d20-grafik](https://user-images.githubusercontent.com/47501072/163419210-aa323b71-a08a-439c-a4dd-4f264f832770.png)

**Comment by MyzerAT** [comment]
Link zum Forum
https://forum.iobroker.net/topic/54195/meross-connection-error-error-0/16

**Comment by Apollon77** [comment]
Working on it

**Comment by Apollon77** [comment]
Please check GitHub version/1.10.5

**Comment by MyzerAT** [comment]
danke funktioniert wider alles!!!!

lg rudi
