### ISSUE TITLE
Mit v1.11.0 laufend Warn-Meldungen

### ISSUE THREAD

**Issue by mcuiobroker** [Apollon77/ioBroker.meross#284]
![image](https://user-images.githubusercontent.com/84818934/171994771-ce91f756-f273-4bca-8dbe-3755815080c0.png)
Bin zurück auf 1.10.5.

**Comment by Apollon77** [comment]
Warum closed? Wen  der Fehler kommt dann ist das gerät nicht erreichbar.

**Comment by mcuiobroker** [comment]
Genau, zu spät bemerkt. Waren zu viele Nachrichten nacheinander. Aber nur 2 Geräte, die aus waren. Also hab wieder 1.11.0. Alles ok. Sorry.
