### ISSUE TITLE
Meross Cloud error: HTTP-Response Error: Error: ETIMEDOUT / Status=--

### ISSUE THREAD

**Issue by caldwell27** [Apollon77/ioBroker.meross#289]
**Describe the bug**  
Since a few weeks ìll always recived the following error: 

HTTP-Response Error: Error: ETIMEDOUT / Status=--

So no new data was synced with the cloud.

What i have tried:
-  Delete and new install the current Adapter
- Create a new meross acount and try with it (same problem)

I am able to control my devices over the app and the homebridge plugin.

Here son debug output:

meross.0 | 2022-07-07 15:28:58.612 | debug | HTTP-Response Error: Error: ETIMEDOUT / Status=--
-- | -- | -- | --
meross.0 | 2022-07-07 15:28:55.604 | debug | HTTP-Call: {"url":"https://iot.meross.com/v1/Device/devList","method":"POST","headers":{"Authorization":"Basic 9a2e14a7355cc4433220e596b29b0b85ebec1c140cc154c43dae5a0d36f8a4de","vender":"meross","AppVersion":"0.4.4.4","AppType":"MerossIOT","AppLanguage":"EN","User-Agent":"MerossIOT/0.4.4.4"},"form":{"params":"e30=","sign":"01100e9bb6cb9a00356e4444327b0819","timestamp":1657200535603,"nonce":"gax65le0l84bepjj"},"timeout":3000}
meross.0 | 2022-07-07 15:28:55.602 | debug | HTTP-Response OK: {"apiStatus":0,"sysStatus":0,"info":"","timeStamp":1657200535,"data":{"userid":"2142732","email":"rene.smole@it-edv-smole.at","key":"171daa4d3e425a4fb0b62ba3e90e3266","token":"9a2e14a7355cc4433220e596b29b0b85ebec1c140cc154c43dae5a0d36f8a4de"}}
meross.0 | 2022-07-07 15:28:52.271 | debug | connected set to false
meross.0 | 2022-07-07 15:28:52.211 | debug | HTTP-Call: {"url":"https://iot.meross.com/v1/Auth/Login","method":"POST","headers":{"Authorization":"Basic ","vender":"meross","AppVersion":"0.4.4.4","AppType":"MerossIOT","AppLanguage":"EN","User-Agent":"MerossIOT/0.4.4.4"},"form":{"params":"eyJlbWFpbCI6InJlbmUuc21vbGVAaXQtZWR2LXNtb2xlLmF0IiwicGFzc3dvcmQiOiJGb3JkTW9uZGVvOTIiLCJtb2JpbGVJbmZvIjp7ImRldmljZU1vZGVsIjoiIiwibW9iaWxlT3NWZXJzaW9uIjoiIiwibW9iaWxlT3MiOiJsaW51eCIsInV1aWQiOiJwdHhoNTNydDBmdnhtdHI4cDgyZGRqdTA2MmkxejdhMzA2NzIxOC1mMzIxLTQyYTgtOTJhZS01ODJjNjUxZWNiZDgiLCJjYXJyaWVyIjoiIn19","sign":"df72388129e4590bd90afe6d02603bdd","timestamp":1657200532210,"nonce":"rh0o4kz2q231j7vo"},"timeout":3000}
meross.0 | 2022-07-07 15:28:52.131 | info | starting. Version 1.12.2 in /opt/iobroker/node_modules/iobroker.meross, node: v16.15.1, js-controller: 4.0.23
meross.0 | 2022-07-07 15:28:51.656 | debug | Plugin sentry Initialize Plugin (enabled=true)
meross.0 | 2022-07-07 15:28:44.989 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
meross.0 | 2022-07-07 15:28:44.988 | debug | Plugin sentry destroyed
meross.0 | 2022-07-07 15:28:44.987 | info | terminating
meross.0 | 2022-07-07 15:28:41.978 | info | Got terminate signal TERMINATE_YOURSELF
meross.0 | 2022-07-07 15:28:12.766 | debug | connected set to false

Iobroker info:

Plattform: docker
Betriebssystem: linux
Architektur: x64
CPUs: 4
Geschwindigkeit: 1501 MHz
Modell: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM: 9.5 GB
System-Betriebszeit: 7 T. 20:32:31
Node.js: v16.15.1
time: 1657200383703
timeOffset: -120
Adapter-Anzahl: 501
NPM: 8.11.0
Datenträgergröße: 3572.2 GB
Freier Festplattenspeicher: 1592.7 GB
Betriebszeit: 3 T. 03:17:02
Aktive Instanzen: 19
Pfad: /opt/iobroker/
aktiv:

**Comment by Apollon77** [comment]
Then in fact the Meross server is not responding withiin 30seconds ti deliver your device list ... 

How many devices you have?

**Comment by Apollon77** [comment]
Hm ... seems their server answer very slow ... you could try a manual change
* check on your iobroker host if /opt/iobroker/node_modules/iobroker.meross/node_modules/meross-cloud/index.js exists ... if not use /opt/iobroker/node_modules/meross-cloud/index.js
* change this line https://github.com/Apollon77/meross-cloud/blob/master/index.js#L93 and asjust the 3000 to e.g. 10000 (3s -> 10s)
* restart adapter
* report result
Normally these 3s timeout are working good ... no idea what is special for your account

**Comment by Apollon77** [comment]
Ok, then I will increase it for a next version in general
