### ISSUE TITLE
Datenabfrage nur wenn Gerät lokal erreichbar

### ISSUE THREAD

**Issue by mcuiobroker** [Apollon77/ioBroker.meross#290]
Warum auch immer? Ich bekam eine Mail (Meross) mit Bezug auf Datenabfrage zu häufig.
Bei mir waren seit einigen Tagen bewusst bestimmte Meross-Steckdosen nicht eingeschaltet und somit nicht lokal und auch nicht über die Cloud online.
Mail mit Daten an ingo@fischer-ka.de geschickt.

**Comment by mcuiobroker** [comment]
localConnection wird `true`angezeigt, obwohl Gerät nicht in der Steckdose?
Sollte eigentlich nach Einstellungszeit (Polling) erkannt werden, oder nicht?
![image](https://user-images.githubusercontent.com/84818934/178380944-a1143a94-8910-49ab-9a27-4648937c400d.png)
Ping -> Zielhost nicht erreichbar.

**Comment by Apollon77** [comment]
Der state erlabt urch "false" setzen zu sagen "mach den bitte nicht zuerst lokal ... Aktuelle Logik ist immer" wenn lokal nicht tut frage die cloud".

ich denke ich mache das konfigurierbar ... wenn lokal - soll cloud überhaupt gefragt werden

**Comment by mcuiobroker** [comment]
Daten angekommen?

**Comment by Apollon77** [comment]
Ja, aber da ist ausser einmal alle ca. 90s ein daten lese call an die cloud für die 3 offline geräte nix drin ... der rest geht nur lokal. Kann natürlich jetzt immer noch sein das auch ein lokaler Call irgenwie doch mit der cloud redet ... was aber blöd wäre :-(

also wir sind noch nicht wirklich schlauer geworden.

Die nächste Version hat eine Einstellung lesecalls immer nur lokal zu machen wenn mal lokal aktiviert hat ...
