### ISSUE TITLE
SmartSmoke Sensor wird nicht erkannt

### ISSUE THREAD

**Issue by mesingerold** [Apollon77/ioBroker.meross#296]
Der Rauchsensor GS559A wird nicht als Device erkannt obwohl er in der Cloud eingebunden ist.
Bitte um Aufnahme als neues Gerät!

Danke

**Comment by Apollon77** [comment]
Hehe, hab auf das Ticket gewartet :-)

Bitte Loglevel der Instanz auf Debug stellen, dann itte alles über die Meross app konfigurieren was da ggf geht und zeitpunkt aufschreiben das ich es mit log matchen kann. Wenns geht den Sensor mal auslösen?
Dann komplettes Debug log von all dem aus dem Logfile auf der Platte unter /opt/iobroker/log/... holen und mir unter referenz auf diees Ticket per email an iobroker@fischer-ka.de senden

**Comment by mesingerold** [comment]
Erledigt!!

**Comment by Apollon77** [comment]
Bitte GitHub version versuchen. Sollte einmal mit einem status Feld drin sein der die 3 werte die im Log waren abbilden kann und ein boolean "alarm" state  (nur bei nem Alrm, nicht bei Test und nicht bei ok).

**Comment by mesingerold** [comment]
Erledigt

**Comment by Apollon77** [comment]
Ok, da fehlt noch was an einer Stelle ... neue GitHub bitte checken

**Comment by Apollon77** [comment]
Ok, hab noch das "interConn" Feld mit hinzugefügt (keine Ahnung was das bedeutet) ... gern bitte nochmal checken neueste GitHub. Wenn alles passt hier bitte kurz schreiben. Brauche kein weiteres Log

**Comment by Apollon77** [comment]
Releasgeht gerade raus

**Comment by mesingerold** [comment]
Hallo Ingo,

Bis jetzt hat alles funktioniert & DANKE
