### ISSUE TITLE
MAP100 support

### ISSUE THREAD

**Issue by HiroP77** [Apollon77/ioBroker.meross#304]
I installed a Meross MAP100 (so called "upgraded version") air Purifier, it basically gets recognized by the adapter but drops a 
"Received unknown data Appliance.Control.FilterMaintenance: {"filter":[{"lmTime":1662013898,"life":100,"channel":0}]}" and a "Please send full line from logfile on disk to developer" every now and them. Seems like the MAP100 is not jet fully supported, a lot of the reported control values are not presented in iobroker.

I will send the complete Logfile to Apollon77 via email.

**Comment by Apollon77** [comment]
E-mail received, will check it as soon as back from vacation next week

**Comment by Apollon77** [comment]
@HiroP77 but you can use the time and please provide another debug log ;-) this time please first use the meross App after that use the hardware device controls and change anything that’s possible there. 

Note down the time and what exactly you changed. Please leave 30 seconds time between the actions that I can find the stuff in the log better. 

Ideally also provide me a screenshot of what you can configure in the app. 

With this I can also see the features and how they are controlled and notified. 

Send via email again please. 

Thank you

**Comment by Apollon77** [comment]
@HiroP77 The github version should at least show the filter data. When you get me the next debug log (see last comment) ideally use thei verion .. or send an additional log with a start with this version that I can check that all works as expected (there are some assumptions in)

**Comment by Apollon77** [comment]
@HiroP77 Did you had a chance to check the Github version or further details ?

**Comment by Apollon77** [comment]
@HiroP77 Anything left?
