### ISSUE TITLE
Werte ändern über den ioBroker

### ISSUE THREAD

**Issue by Notch001** [Apollon77/ioBroker.meross#306]
Ich kann die Werte beim Thermostat nicht ändern. Wenn ich den DP 'current set' auf 29 Grad Stelle, wird dieser nicht vom Thermostat angenommen bzw an ihn geschickt. 

Ich nutze die 1.14 von Adapter

- Iobroker 
- Raspian

**Comment by Apollon77** [comment]
Ja, weil currentTemp die aktuelle Temperatir ist die an sich nicht schreibbar ist. Kann das sein?
statt desses sollte es auch einen targetTemp State geben ... nimm den mal

Ansonsten bitte Loglevel der Instanz auf Debug setzen und so eine aktion als Log zeigen

**Comment by Notch001** [comment]
Moin Ingo,

Vielen Dank für deine Antwort. Habe nochmal nachgeguckt. Ich habe leider keinen state 'targetTemp' wenn ich in der App die Temperatur änder, dann änder sich im Iobroker die currentTemp. Ich hab dir Mal das Modell vom Thermostat und die DP's aus'm ioBroker angehängt.

Am 16. Sept. 2022, 23:56 +0200 schrieb Ingo Fischer ***@***.***>:

**Comment by Apollon77** [comment]
Bitte vollständiges Debug log vom Start und dso einer Aktion anhängen (nocht per email replien, das ignoriert attachements). Oder per E-Mail an iobroker@fischer-ka.de mit Referenz auf dieses Issue.

**Comment by Apollon77** [comment]
Ok, also ein Thermostat über den Hub (das war die Info die fehlte) ändert man über currentSet. Das ist korrekt. Aber scheinbar geht da was nicht mehr ... ging früher mal.

Bitte mal neues log erzeugen indem Du:
* einmal "custom" setzt. übernimmt er das?
* in der App die Temperatur setzt 

Ingo

**Comment by dp20eic** [comment]
> Moin Ingo, Vielen Dank für deine Antwort. Habe nochmal nachgeguckt. Ich habe leider keinen state 'targetTemp' wenn ich in der App die Temperatur änder, dann änder sich im Iobroker die currentTemp. Ich hab dir Mal das Modell vom Thermostat und die DP's aus'm ioBroker angehängt. Am 16. Sept. 2022, 23:56 +0200 schrieb Ingo Fischer ***@***.***>:
> […](#)
> Ja, weil currentTemp die aktuelle Temperatir ist die an sich nicht schreibbar ist. Kann das sein? statt desses sollte es auch einen targetTemp State geben ... nimm den mal Ansonsten bitte Loglevel der Instanz auf Debug setzen und so eine aktion als Log zeigen — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Guten Morgen,

ich habe die "meross mts100h" bei mir funktionieren die sie wie sie sollen.

meross.0.hubid.mtsid.**currentSet** = Zeigt mir die Temperatur an die durch die verschiedenen Modi° ausgewählt werden
meross.0.hubid.mtsid.**custom** = ist zum setzen der Temperatur im Modus manuell

°modi = Manuell (0), Comfort(1), Economy(2), Automatik(3) u. Away(4)
.........................|.......................|..........................|...........................|..........................|___ wird in der APP über Modus-Temperatur eingestellt
.........................|.......................|..........................|...........................|__ Nimmt die in der APP hinterlegte Schedules
.........................|.......................|..........................|___ wird in der APP über Modus-Temperatur eingestellt
.........................|.......................|___ wird in der APP über Modus-Temperatur eingestellt
.........................|__ wird über den Slider in der APP o. die Tasten am MTS100h eingestellt und entspricht dem **custom**

Ich habe mir aus den meross-DP aliase angelegt und in iqontrol dann so
![image](https://user-images.githubusercontent.com/71387331/191660715-82f35a41-3687-4d52-90a8-972827987e49.png)
![image](https://user-images.githubusercontent.com/71387331/191661309-fbdd932c-c791-468e-bb98-3079a6bee34e.png)

Visualisiert.

VG
Bernd

**Comment by Apollon77** [comment]
> P.S.: currentSet ist aktuell "read/write" sollte aber nur lesend sein, oder??

Ich denke das ist die relevante Frage ... "früher" als ich es mal eingebaut habe was es setzbar. Inzwischen scheinbar nicht mehr. der es geht nur bei einer der Thermostat-Generationen.
Aber scheibar ists ja gesolved

**Comment by dp20eic** [comment]
> > P.S.: currentSet ist aktuell "read/write" sollte aber nur lesend sein, oder??
> 
> Ich denke das ist die relevante Frage ... "früher" als ich es mal eingebaut habe was es setzbar. Inzwischen scheinbar nicht mehr. der es geht nur bei einer der Thermostat-Generationen. Aber scheibar ists ja gesolved

ob @Notch001 es gelöst hat kann ich nicht sagen, wollte nur meine Lösung zeigen.

**Comment by Notch001** [comment]
Nee, es ist noch nicht gelöst. Nutze jetzt die Automatik Funktion in der meross App.
Bin leider zeitlich etwas eingeschränkt und deshalb noch nicht wieder hinterher gewesen.
Am 10. Okt. 2022, 18:17 +0200 schrieb dp20eic ***@***.***>:
