### ISSUE TITLE
Meross Device MSS550l - no longer online

### ISSUE THREAD

**Issue by brkuser112** [Apollon77/ioBroker.meross#325]
**Describe the bug**  
Devices could be used for more than 1 year. Since the last 3-4-5 month adapter always offline, but online in the Meross App. 

**To Reproduce**  
1. Go to '...' objects
2. Click on '...' meross - 0
3. Scroll down to '....' device
4. See error - offline

**Expected behavior**  
Device online. 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.14.0
 - JS-Controller version: 4.0.23
 - Node version: v16.17.1
 - Operating system: raspberry pi - linux

**Additional context**  
n.a.

**Comment by Apollon77** [comment]
Ok, the log shows the following:
* EHOSTUNREACH erros on both devces mean that the device is NOT in the local network available and the IP listed inn log/with device is NOT in the network at all. Please check that the IP is set correctly in the states (not that the IP changed?) or that the device is really having good WLAN reachability ...
* Timouts on local connection could also mean wrong IP or just bad WLAN
* Maybe try to power off/on the devices
* The Adapter also tries no Cloud communication fallback ... if you like that you need to enable that (you disabled it). Check the device states and adapter config

**Comment by brkuser112** [comment]
Thanks for helping.
That two devices are not in the LAN and the settings in the Meross Instance was wrongly configured to "only local communication".
Sorry for that.

**Comment by Apollon77** [comment]
So fixed now?

**Comment by brkuser112** [comment]
Fixed now! Thanks
