### ISSUE TITLE
New device MS100F support

### ISSUE THREAD

**Issue by mesingerold** [Apollon77/ioBroker.meross#342]
Hallo,

the new device „MS100F“ isn’t jet supported!
Please implement it in your adapter, debug sent via email

Thank´s a lot

**Comment by Apollon77** [comment]
What is it for a device?

**Comment by mesingerold** [comment]
Hallo Ingo,Es handelt sich dabei um einen Temp-& Feuchtichkeitssensor für HomekitSmart Temperature and Humidity Sensor Kit - MS100Fmeross.comDanke & LGAm 22.06.2023 um 10:52 schrieb Ingo Fischer ***@***.***>:﻿
What is it for a device?

**Comment by Apollon77** [comment]
Please send a full debug log of adapterstart with info abotu whcih device it is

**Comment by mesingerold** [comment]
Hallo,

since the last firmware-update everything works like expected!

THX
