### ISSUE TITLE
Getting frequent iobroker warnings "Can not get Physical Lock data for Device ..."

### ISSUE THREAD

**Issue by catmountains** [Apollon77/ioBroker.meross#346]
**Describe the bug**  
I have several meross devices (i.e msg100, mss425e, mss310) and they work fine with iobroker. I also have the smart thermostat mts200. The device also works fine with iobroker, for example I can set the temperature and can turn it on or off. However, I get the following messages frequently in the iobroker log:

meross.0 | 2023-08-09 18:52:38.688 | warn | Can not get Physical Lock data for Device 2206246949270660120148e1e999c00f: Error: Timeout / {"lock":[{"onoff":null,"channel":0}]}
-- | -- | -- | --
meross.0 | 2023-08-09 18:52:38.688 | warn | Can not get Physical Lock data for Device 2206246949270660120148e1e999c00f: Error: Timeout / undefined

**To Reproduce**  
Setup the smart thermostat mts200 in the meross cloud and restart the meross iobroker adapter

**Expected behavior**  
get rid of these messages

**Screenshots & Logfiles**  
![image](https://github.com/Apollon77/ioBroker.meross/assets/141858410/900d3f77-2ae5-4a96-940e-6bf8e1ad0ba5)

**Versions:**  
 - Adapter version: 1.15.1
 - JS-Controller version: 4.0.24
 - Node version: 18.17.0
 - Operating system: raspberry pi os 5.10.63-v7l+

**Additional context**  
n/a

**Comment by Apollon77** [comment]
Is the mentioned device online? maybe try restarting it? In fact the devcie mentioned there is giving a timeoiut while reading physical lock data.

**Comment by catmountains** [comment]
The device is online. I can control it using either the meross app or Apple Home Kit. When I restart the meross Adapter instance in ioBroker, the device is online (in ioBroker) for a short time (a minute or so) but then goes offline and the messages appear in the log.

**Comment by Apollon77** [comment]
maybe it do not like to be queried locally? Maybe disable this for the device and try if it works using cloud

**Comment by catmountains** [comment]
Thanks. I disabled the device (setting disabled=true under the device object) and the messages stopped. This workaround works for me.

**Comment by Apollon77** [comment]
Interesting case ... seems tat some thermostats also report yphsical lock but then do not return data ... next version ignores this
