### ISSUE TITLE
ms100 bei den Werten fehlt das Komma 

### ISSUE THREAD

**Issue by walterhosner** [Apollon77/ioBroker.meross#349]
Hallo 
bei den ms100 werden die Werte
200° Angezeigt anstelle 20.0°
![image](https://github.com/Apollon77/ioBroker.meross/assets/136177997/14bd4f94-d04b-468e-9b91-8848fc1b958a)

[neu 1.txt](https://github.com/Apollon77/ioBroker.meross/files/13467383/neu.1.txt)

**Comment by Apollon77** [comment]
@walterhosner Could it be that this only happens on the adapterstart andthat all temperature/humdity updates afterwards are shown correctly

**Comment by Apollon77** [comment]
@walterhosner Please install GitHub version, restart the instance once afterwrads. Fixed now?

**Comment by walterhosner** [comment]
@Apollon77 schaut gut aus
![image](https://github.com/Apollon77/ioBroker.meross/assets/136177997/7602e0ff-5264-4068-a29b-ea38b29a01d5)

**Comment by Apollon77** [comment]
Super, release auf dem weg
