### ISSUE TITLE
"Smart Elektrische Thermostat, Fußbodenheizung WLAN Raumthermostat in Weiß" communication not working since version 1.15 

### ISSUE THREAD

**Issue by CodeZeroOneTwo** [Apollon77/ioBroker.meross#358]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
With version 1.12.2 the Thermostat works fine, with Version 1.15 or above the object "online" goes false an the communication works only in one direction. I can see in the iobroker objects when i change the target-temp with the app but when i change the target-temp object in iobroker the thermostat doesn't accept the change. When i go back to Version 1.12.2 all works fine again. The problem was with various Instalations. First i run iobroker on a VM with Linux-Mint the Ubuntu-Server and at the moment on a Ubuntu-Desktop host as a Docker-Container.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.12.2;1.15
 - JS-Controller version: 5.0.17 
 - Node version: v18.19.0 
 - Operating system: linux ubuntu 22.04 x64

**Additional context**  
[meross.0.txt](https://github.com/Apollon77/ioBroker.meross/files/13854155/meross.0.txt)

**Comment by Apollon77** [comment]
Hnm,,, 1.15 is really old ... would you mind trying current versions? :-)
If it still happens with 1.17 please provide a log and please also state when you tried what (time wise), else I can just guess what I see in the logs

**Comment by CodeZeroOneTwo** [comment]
Hello,

The problem has fixed itself. Meross has apparently updated the thermostat
yesterday. After this, the adapter no longer worked with version 1.12.2, so
I had the same problem as before when I upgraded to 1.15. I then upgrade
The Adapter to version 1.17 and everything worked again. But thanks for the
help.

Regards Patrick

Ingo Fischer ***@***.***> schrieb am So. 7. Jan. 2024 um
18:24:
