### ISSUE TITLE
Adapter ist sehr oft offline

### ISSUE THREAD

**Issue by uwe72** [Apollon77/ioBroker.meross#364]
Ich habe mal protokolliert wann der Adapter offline geht. Dies ist leider über den Tag hinweg sehr oft der Fall. Haben andere auch das Problem bzw. was kann man dagegen tun?

![image](https://github.com/Apollon77/ioBroker.meross/assets/61848539/39a77565-f2c9-4105-ad7c-6e2caa75f5ba)

![image](https://github.com/Apollon77/ioBroker.meross/assets/61848539/cde7d3f4-4a61-4d15-9fe0-7e4b30f43ad2)

Man sieht hier, dass der Adapter sehr oft für 3 Sekunden offline ist:
![image](https://github.com/Apollon77/ioBroker.meross/assets/61848539/6fa454d5-d7d1-494b-b926-20df67615b3f)

**Comment by Apollon77** [comment]
Dann provide doch mal ein Logfile, vllt Debug log? Wenn Du viele Energiemesssteckdosenhast vllt auch mal das Abfrageinterval höher setzen, vllt its zu viel

**Comment by uwe72** [comment]
@Apollon77 
Anbei das Logfile

[meross.log](https://github.com/user-attachments/files/15789241/meross.log)

**Comment by Apollon77** [comment]
Hm ... why there is a 5 minute restart in that? 

2024-06-11 15:38:07.912	debug	Schedule restart: * */5 * * *

So you configurted that instance to restart every 5 minutes which sets connection state to false and reinitialize anything ... thats also prodices a lot of traffic to meross ... but this is not the issue in my eyes becaus eit seems that this schedule is executed way too often and aldo faster then 5minutes. Please clear this restart schedule and check if it is better then

**Comment by Apollon77** [comment]
![IMAGE 2024-06-12 11:19:08](https://github.com/Apollon77/ioBroker.meross/assets/11976694/236f74f9-9dfb-4938-81ad-932ccc4d1340)

Ok I read the scheulw rong ... you really requested a restarted EVERY MINUTE in every 5th hour :-)

**Comment by uwe72** [comment]
ok, probably the trigger was wrong. i deleted it now. We will see how works now.......i added the restarting-trigger because of strange behavior. Give me 24h in order to see how works now.....Thanks already for the hint!!

**Comment by Apollon77** [comment]
Please reopen if still an issue
