### ISSUE TITLE
missing device: MSG200 (3xGarage opener)

### ISSUE THREAD

**Issue by dagobertch** [Apollon77/ioBroker.meross#367]
My Device get not connected, I have seen MSG100 is implemented, maybe MSG200 is missing?

**Comment by Apollon77** [comment]
Please post a full debug log. In forum there was the report that it worked without any issue

**Comment by dagobertch** [comment]
Dont know exactly what I have done. After Update of some iobroker components, the Garage door opener works…
Sorry and thanks
Chris
