### ISSUE TITLE
Add Option to control the LED

### ISSUE THREAD

**Issue by DeamBeam** [Apollon77/ioBroker.meross#6]
I would like to have an option, to control the LED.
I want to be able to control the LED of my meross over iobroker.
Example: turn off the LED autmaticly at night, so i dont have to go in the app for it.

**Comment by Apollon77** [comment]
Is this possible via the app?
Which device type?

**Comment by DeamBeam** [comment]
I have the mss425 Meross-Surge-Protector.
On the app you need to go on your device and then on the option button on the upper-right corner and then you should notice the LED slider.

**Comment by Apollon77** [comment]
Ok i need the hollowing from you:

Start adapter then change led in the app for all possible options. Then check the log ... you should find some log entries about unknown messages and such. Collect this log output but not from Admin but from file on disk and attach here.

**Comment by DeamBeam** [comment]
I can't find any log entries from the meross-adapter.
Here are some screenshots from the app:
![image](https://user-images.githubusercontent.com/43090270/52168709-829f4b80-272d-11e9-8bca-15a274c7e8ab.png)
![image](https://user-images.githubusercontent.com/43090270/52168711-892dc300-272d-11e9-9ebd-b0a54c4b0a71.png)
![image](https://user-images.githubusercontent.com/43090270/52168714-8df27700-272d-11e9-911a-a3bbf98d0492.png)

**Comment by Apollon77** [comment]
Ok, I found it, it is the "DNDMode". Problem: CHnges are not pushed via MQTT, so we can read the status and also change from ioBroker, but changes are not reported to the adapter, so we would need to poll. Is this really that interesting to add polling there?

**Comment by DeamBeam** [comment]
Not anymore, because i just have deactivated the led all the time. 
But i wouldn't need a polling, because i would only change it over iobroker, because i barely use the meross app.

**Comment by Apollon77** [comment]
This would work, it will go out of sync as soon as a user uses meross app ... I will think about it

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/26953/test-meross-adapter-1-2-x Please test and provide Feedback
