### ISSUE TITLE
Password length

### ISSUE THREAD

**Issue by Hamsterrennen** [Apollon77/ioBroker.meross#63]
Hi there :-),

I tried to connect to the meross cloud by this adapter.
I got the following error in the log:
`Meross Connection Error: Error: 1004: Add Login Token failed, code: 1004, reason:Username is not exist or password is wrong email: xx@xx.de`

I wondered, why this happened and double-checked my password. It was the right one.
Then i checked your source code and found the following part:

`// Maximum password length supported by cloud is 15 characters
    if (adapter.config.password.length > 15) {
        adapter.config.password = adapter.config.password.substring(0, 15);`

I noticed that my password length is above 15. That means, that it's possible to register a password with more than 15 characters at the meross cloud.
After changing my password to the size of 15 the adapter worked fine.

Please add a error message or log entry if the password is longer than 15 characters.

Thanks,
Hamsterrennen

**Comment by Apollon77** [comment]
The code is that way because as I implemented the adapter they simply cutted after 15 characters ... maybe they changed that now ...  Then I can remove that ... Could you please try to remove this line and use a longer passwort and see if it works?

**Comment by Apollon77** [comment]
Did you had a chance to test it?

**Comment by Hamsterrennen** [comment]
No, sorry i couldn't test it right now.
I'll test it if I find time the next days.

**Comment by Apollon77** [comment]
test 1.4.0 please
