### ISSUE TITLE
Meross Steckdosen de/aktivieren 

### ISSUE THREAD

**Issue by MyzerAT** [Apollon77/ioBroker.meross#84]
Hallo Apollon, 

Ich habe einige Meross Steckdosen die ich für Weihnachtsbeleuchtung verwende (10Stück) die Weihnachtsbeleuchtung ist aber abgebaut, da Weihnachten ja schon vorbei ist. Nun werden die Meross Steckdosen nicht mehr erreicht, was klar ist und meine logs gehen über mit Fehlermeldungen:

meross.0	2020-03-21 16:21:56.668	warn	Can not get Abilities for Device 1811303935030425182134298f187dde: Error: Timeout / undefined

Gibt es eine Möglichkeit diese Meldungen, bzw. die Steckdosen als deaktiviert zu flaggen ?

thx u. lg Rudi

**Comment by mrfenyx** [comment]
Vielleicht auch damit verbunden: wenn man aus der Meross App ein Gerät löscht, bleiben die DPs vorhanden und die selbe Warnung wird angezeigt.

**Comment by Apollon77** [comment]
Ein adapter restart sollte letzteres aber fixen oder?!

**Comment by mrfenyx** [comment]
Hi,
leider nein. Hier 2 Bilder, einmal die App, einmal Objekte in ioBroker:
![image](https://user-images.githubusercontent.com/2023454/95688938-efaafa00-0c0d-11eb-80fe-25e13cc4aded.png)

![image](https://user-images.githubusercontent.com/2023454/95688931-dace6680-0c0d-11eb-9adf-65cff4b83d65.png)

Das Gerät "Mansarda" ist in der App nicht mehr da aber im Adapter schon. Soll ich dafür vielleicht ein neues Issue eintragen?

**Comment by Erbse69** [comment]
Hallo Apollon,
Auch ich habe einige Meross Steckdosen Dank deines tollen Adapters im Einsatz. Aber leider quillt auch mein Log über mit Warnungen wenn eine davon nicht erreichbar ist. Wäre das vielleicht über eine Checkbox in der Adapterkonfiguration lösbar? Sowas wie "Warnung für nicht erreichbare Geräte unterdrücken"?
Viele Grüße,
Stefan

**Comment by elzershark** [comment]
Version 1.5.1
Warnungen werden bei mir nicht angezeigt. Kann aber an den Geräten liegen die man hat.
Grad mal getestet mit Steckdosenleisten.
Wenn Geräte nicht vorhanden sind, stoppe ich den Adapter. Lösche den Datenpunkt des Gerätes und starte Ihn wieder.

**Comment by gitknd** [comment]
Ich würde mich über ein entsprechendes Feature im Adapter zum
a) entfernen
b) deaktivieren/aktivieren
auch sehr freuen. Mir geht es ähnlich, dass ich immer wieder Geräte habe, die nur phasenweise in Betrieb sind.

**Comment by sckibo** [comment]
Sehe ich genauso - ich bekomme auch immer 'warn' Meldungen, wenn die Steckdosen offline sind. Es wäre schön, wenn man diese Meldungen loswerden könnte.

**Comment by Apollon77** [comment]
Please try GitHub version ... it is a bigger version update and could contain issues, but my tests were positive so far. I introduced a "disabled" state per device. Set to true to not log that one error message as info (but still as debug and also still try to reconnect every 60s). Is this what you wanted? :-)

**Comment by Apollon77** [comment]
Additionally the newst GitHub tries to communicat locally first ...  If someone has devices with energy consumption it would be cool to get a debug log ... waant to see if the enegery values coming locally ... then we could think about increasing the poll interval again or such

**Comment by Erbse69** [comment]
> Please try GitHub version ... 

I have just tested the GitHub version. Unavailable devices "Can not get Data for Device..." are now logged as info, no longer as warning. For me that's fine, but maybe someone would still like to have it as a warning. Maybe a global setting in the instance e.g. "Log Level for unavailable devices" with a drop-down list to choose from (debug,info,warning,error) would be perfect. 

The new disable state also works. If set to true the log entry for this device is supressed.

Thank you very much for your effort!

**Comment by Erbse69** [comment]
> If someone has devices with energy consumption it would be cool to get a debug log ... 

tested with MSS310EU

```
meross.0
2022-01-08 16:05:07.878	debug	HTTP-Local-Response OK 19090985932229251h1648e1e904xxxx: {"header":{"messageId":"2ed058a09b6be2645de8e202429a7576","namespace":"Appliance.Control.Electricity","method":"GETACK","payloadVersion":1,"from":"/appliance/19090985932229251h1648e1e904xxxx/publish","timestamp":1641654307,"timestampMs":626,"sign":"5be12586b87ece3a681dba2b561c5cb5"},"payload":{"electricity":{"channel":0,"current":0,"voltage":2312,"power":0,"config":{"voltageRatio":188,"electricityRatio":100}}}}

meross.0
2022-01-08 16:05:07.859	debug	HTTP-Local-Call 19090985932229251h1648e1e904xxxx: {"url":"http://192.168.1.113/config","method":"POST","json":{"header":{"from":"/app/122101-aab7c38c9c515dcc63747a03a2ecd7c5/subscribe","messageId":"2ed058a09b6be2645de8e202429a7576","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"b5e6c3c0ac3036481ce5ee28f724e314","timestamp":1641654308},"payload":{}},"timeout":3000}

meross.0
2022-01-08 16:05:07.858	debug	19090985932229251h1648e1e904xxxx Electricity query executed now
```

**Comment by Apollon77** [comment]
@Erbse69 

> Maybe a global setting in the instance e.g. "Log Level for unavailable devices" with a drop-down list to choose from (debug,info,warning,error) would be perfect.

Thank you for the idea, but I think it is fine witth "Info" or "debug" depending on the "disabled" flag.

> tested with MSS310EU

Cool ....

**Comment by Erbse69** [comment]
> Thank you for the idea, but I think it is fine witth "Info" or "debug" depending on the "disabled" flag.

But this is different to the old version:

- Old version: Unavailable devices generate a **warning entry** in the log
- New version: Unavailable devices generate an **info entry** in the log or **no entry at all** if the disable object is set to true

For me this is fine. I was just thinking of other users who maybe still want to have a warning.

**Comment by Apollon77** [comment]
> I was just thinking of other users who maybe still want to have a warning.

I think noone will really care :-))  if someone wants to monitor it he should use the states
