### ISSUE TITLE
Daten für Verbrauch bei MSS310

### ISSUE THREAD

**Issue by dmw02** [Apollon77/ioBroker.meross#85]
Wäre es möglich Daten wie Tagesverbrauch, Monatsverbrauch und Gesamtverbrauch in kWh zu implementieren?

**Comment by tommyMX** [comment]
any news on this?

**Comment by tommyMX** [comment]
both threads are closed

**Comment by Apollon77** [comment]
what's closed? this one is open and flagged as "enhancement" as it should be.

If I find thime - or anyone else provides an PR, the feature will be there maybe somewhen

**Comment by tommyMX** [comment]
okay okay....

i dont understand why some specials are in the app like the month view and not to find in the objects from the adapter..

sorry that i asked...

i also tried the virtuelpowermeter but seems also not working..

have a nice day

**Comment by Apollon77** [comment]
> sorry that i asked...

no need for that ... asking is always allowed :-)

The main reason that the data are not there is to find a proper structure to hold the data that it makes sense to use them in iobroker ... so it would also help to understand the usecase

**Comment by Jowelli** [comment]
I think it would be great to have the daily, weekly, monthly and total energy consumption available in the iobroker meross adapter. I have already used the TP-LINK HS100 devices and adapter but this doesn´t have the total energy consumption availabel in the device, thats bad, see the attached screenshot. So I decided to use the meross MSS310...  very good devices , but the consumption values are missing. Could you please add these values to the adapter?
![31-01-_2022_16-20-48](https://user-images.githubusercontent.com/98742720/151820881-9503d9ec-f5fa-467c-9bdd-7eb4bc2ee513.jpg)

**Comment by Jowelli** [comment]
I would send you a device for long time testing, Please tell me if I shall do that. It would be great if you could enhance this adapter   with the energy consuption values. Thank you very much.

**Comment by jroegner** [comment]
Any news on this? Power consumption in IObroker objects would be great for MS310.

**Comment by Apollon77** [comment]
Not yet had time

**Comment by Apollon77** [comment]
Hey giys, someone here and up for some testing starting tomorrow ??? Respond here please. Todo would be update from github and providing a debug log ... then I add some states and you can test again

**Comment by DEV2DEV-DE** [comment]
> Hey guys, someone here and up for some testing starting tomorrow ??? Respond here please. Todo would be update from github and providing a debug log ... then I add some states and you can test again

Ich stünde für Tests zur Verfügung.
kann ich schon von GitHub installieren?

Gruß Bernd

P.S.: Frohes Neues!

**Comment by Apollon77** [comment]
meld emich hier ... dauer nnoch kurz. Ackerenoch durch meine Mails von heute

**Comment by Apollon77** [comment]
@DEV2DEV-DE Frohes neues ebenso!

Bitte GitHub version installieren, dann einfach restarten (braucht kein Debug log). Ich hab es erstmal so gebaut das er beim start einmalig pro Gerät, was es kann, zwei Logzeilen in info Log loggt "Consumption" und "ConsumptionX" ... die würd ich gern mal sehen

**Comment by DEV2DEV-DE** [comment]
Wenn ich über GitHub installiere, erhalte ich Version 1.14.0 - also die Version die auch im Stable ist.
Im Protokoll (info) sehe ich garnix beim Neustart. Muss ich einen bestimmten Branch installieren?

**Comment by Apollon77** [comment]
Ja verion ist korrekt weil ich sie nicht erhöht habe. Ok mach nochmal, müsste jetzt 1.14. sein. wenn das nicht tut bitte debug log und mir per email schicken (iobroker@fischer-ka.de)

**Comment by helfi9999** [comment]
@Apollon77 
 Hi, habe die MSS310 wie kann ich dir helfen??

MfG
helfi

**Comment by Apollon77** [comment]
Danke.siehe letzter Post. Github Version bitte installieren. Fall beim restart danach kein info log mir Consumption beim start kommt bitte ein debug log

**Comment by helfi9999** [comment]
> 

<html>
<body>


2023-01-03 07:25:09.433 | info | 2102030994193390841348e1e94a5570 ConsumptionX: {"consumptionx":[{"date":"2022-12-31","time":1672527489,"value":1287},{"date":"2023-01-01","time":1672613884,"value":0},{"date":"2023-01-02","time":1672700280,"value":1210},{"date":"2023-01-03","time":1672727100,"value":0},{"date":"2022-12-19","time":1671490689,"value":0},{"date":"2022-12-20","time":1671577083,"value":0},{"date":"2022-12-21","time":1671663489,"value":0},{"date":"2022-12-22","time":1671749884,"value":0},{"date":"2022-12-23","time":1671836288,"value":0},{"date":"2022-12-24","time":1671922684,"value":1017},{"date":"2022-12-25","time":1672009088,"value":0},{"date":"2022-12-26","time":1672095484,"value":1534},{"date":"2022-12-27","time":1672181889,"value":180},{"date":"2022-12-28","time":1672268284,"value":0},{"date":"2022-12-29","time":1672354689,"value":895},{"date":"2022-12-30","time":1672441084,"value":0}]}
-- | -- | --
meross.0 | 2023-01-03 07:25:09.316 | info | 2102038438063990841348e1e94a7d24 ConsumptionX: {"consumptionx":[{"date":"2022-12-31","time":1672527480,"value":1243},{"date":"2023-01-01","time":1672613884,"value":0},{"date":"2023-01-02","time":1672700289,"value":663},{"date":"2023-01-03","time":1672727101,"value":0},{"date":"2022-12-19","time":1671490682,"value":0},{"date":"2022-12-20","time":1671577088,"value":0},{"date":"2022-12-21","time":1671663482,"value":0},{"date":"2022-12-22","time":1671749887,"value":0},{"date":"2022-12-23","time":1671836283,"value":0},{"date":"2022-12-24","time":1671922688,"value":569},{"date":"2022-12-25","time":1672009083,"value":0},{"date":"2022-12-26","time":1672095489,"value":1223},{"date":"2022-12-27","time":1672181884,"value":0},{"date":"2022-12-28","time":1672268289,"value":0},{"date":"2022-12-29","time":1672354684,"value":785},{"date":"2022-12-30","time":1672441089,"value":0}]}


</body>
</html>

**Comment by Apollon77** [comment]
Cool. Gibts auch Zeilen mit nur "consumption"? Und nicht nur consumptionX?

**Comment by DEV2DEV-DE** [comment]
`
meross.0 | 2023-01-03 07:48:33.903 | info | 2104171240093290849948e1e96d0324 ConsumptionX: {"consumptionx":[{"date":"2022-12-31","time":1672527489,"value":493},{"date":"2023-01-01","time":1672613882,"value":510},{"date":"2023-01-02","time":1672700284,"value":504},{"date":"2023-01-03","time":1672728474,"value":169},{"date":"2022-12-05","time":1670281087,"value":517},{"date":"2022-12-06","time":1670367489,"value":494},{"date":"2022-12-07","time":1670453880,"value":487},{"date":"2022-12-08","time":1670540283,"value":497},{"date":"2022-12-09","time":1670626685,"value":493},{"date":"2022-12-10","time":1670713088,"value":515},{"date":"2022-12-11","time":1670799480,"value":497},{"date":"2022-12-12","time":1670885883,"value":509},{"date":"2022-12-13","time":1670972285,"value":472},{"date":"2022-12-14","time":1671058687,"value":506},{"date":"2022-12-15","time":1671145081,"value":431},{"date":"2022-12-16","time":1671231484,"value":452},{"date":"2022-12-17","time":1671317886,"value":431},{"date":"2022-12-18","time":1671404288,"value":392},{"date":"2022-12-19","time":1671490681,"value":447},{"date":"2022-12-20","time":1671577084,"value":434},{"date":"2022-12-21","time":1671663486,"value":446},{"date":"2022-12-22","time":1671749889,"value":470},{"date":"2022-12-23","time":1671836281,"value":497},{"date":"2022-12-24","time":1671922683,"value":536},{"date":"2022-12-25","time":1672009086,"value":513},{"date":"2022-12-26","time":1672095489,"value":485},{"date":"2022-12-27","time":1672181881,"value":458},{"date":"2022-12-28","time":1672268283,"value":503},{"date":"2022-12-29","time":1672354685,"value":486},{"date":"2022-12-30","time":1672441087,"value":475}]}
-- | -- | -- | --
meross.0 | 2023-01-03 07:48:33.893 | info | 2104173641238790849948e1e96cbf7c ConsumptionX: {"consumptionx":[{"date":"2022-12-31","time":1672527480,"value":0},{"date":"2023-01-01","time":1672613880,"value":0},{"date":"2023-01-02","time":1672700280,"value":0},{"date":"2022-12-05","time":1670281088,"value":0},{"date":"2022-12-06","time":1670367488,"value":0},{"date":"2022-12-07","time":1670453889,"value":0},{"date":"2022-12-08","time":1670540289,"value":0},{"date":"2022-12-09","time":1670626689,"value":0},{"date":"2022-12-10","time":1670713089,"value":0},{"date":"2022-12-11","time":1670799489,"value":0},{"date":"2022-12-12","time":1670885889,"value":0},{"date":"2022-12-13","time":1670972289,"value":0},{"date":"2022-12-14","time":1671058689,"value":0},{"date":"2022-12-15","time":1671145089,"value":0},{"date":"2022-12-16","time":1671231489,"value":0},{"date":"2022-12-17","time":1671317889,"value":0},{"date":"2022-12-18","time":1671404289,"value":0},{"date":"2022-12-19","time":1671490689,"value":0},{"date":"2022-12-20","time":1671577089,"value":0},{"date":"2022-12-21","time":1671663480,"value":0},{"date":"2022-12-22","time":1671749880,"value":0},{"date":"2022-12-23","time":1671836280,"value":0},{"date":"2022-12-24","time":1671922680,"value":0},{"date":"2022-12-25","time":1672009080,"value":0},{"date":"2022-12-26","time":1672095480,"value":0},{"date":"2022-12-27","time":1672181880,"value":0},{"date":"2022-12-28","time":1672268280,"value":0},{"date":"2022-12-29","time":1672354680,"value":0},{"date":"2022-12-30","time":1672441080,"value":0}]}
`

**Comment by Apollon77** [comment]
Ok, my idea is the following:
* own "consumption polling interval" that polls the status ... default every 15 minutes for the beginning ... How often we can do that we need to see, else Meross will block the Access as we know already from enery states
* state for "consumption sum today" (which should then reset 0:00)
* and one state for consumption yesterday which is kind of the "end sum of yesterday"

Because the data is "30-31 days rolling" I can not calculate a monthly value. For weekly I will not start to mes around with "does a week start sunday or monday". I also think it do not make any sense to have states for "each of thelast 30 days".
With the above two values and pot other adapters like statistics or such all other things could be done

Opinions?

**Comment by Apollon77** [comment]
Ok ... if you like: Update from GitHub, I realized what described above ... Please check

**Comment by DEV2DEV-DE** [comment]
You should spent a unit when creating the states ;-)

![grafik](https://user-images.githubusercontent.com/95883579/210416912-0bda8390-8219-41ce-aca9-66ccce5bd2cf.png)

**Comment by Apollon77** [comment]
@DEV2DEV-DE That costs extra *gg* ... GitHub updated ... (it's kWh)

makes it sense that way?

If helpful I could add a json state also with the raw data ... any opinions?

**Comment by Apollon77** [comment]
Oook ... GitHub updated again ... new state "data" which contains stringified raw data

**Comment by Apollon77** [comment]
Released
