### ISSUE TITLE
New device: Rsg100

### ISSUE THREAD

**Issue by madjack84** [Apollon77/ioBroker.meross#95]
Hey,

The garagedoor opener: Refoss RSG100 is a meross device 
https://www.amazon.de/dp/B07TB3JBNW/ref=cm_sw_r_other_apa_i_lPiNEbY95V62X

![Screenshot_20200419-193302](https://user-images.githubusercontent.com/24653087/79695031-a2f4f080-8274-11ea-9e3c-28bf459816f2.png)

Is it possible to integrate this?

**Comment by Apollon77** [comment]
The msg100 is integrated ... for rsg100 i need the following:
Please enable debug log (intances - expert mode - column loglevel). Then the adapter restarts.
Then best control the rsg100 device using the Meross App or (if possible) with buttons directly and note the exact TIME with "when you did what action how/where".

Then collect the complete log of the adapter start and all these actions from the logfile on disk (iobroker directory, sub dir log) and post here or send me via email (ioboroker@fischer-ka.de).

Then I can have a look

**Comment by oberonn** [comment]
The adapter works for the RSG100 as is, did you already integrate it ?

**Comment by Apollon77** [comment]
I did nothing ... In fact the msg100 is relatively generic, maybe it is the same :-) So we can close here?

**Comment by oberonn** [comment]
denke schon ... 

> I did nothing ... In fact the msg100 is relatively generic, maybe it is the same :-) So we can close here?

denke schon

**Comment by madjack84** [comment]
We installed the RSG100 two days ago. It works like a charm. :)
Meross - refoss and many more seem only to be franchises
