### ISSUE TITLE
Meross Connection Error: Error: 1004: A

### ISSUE THREAD

**Issue by peterbaumert** [Apollon77/ioBroker.meross#98]
2020-04-21 20:37:53.514  - info: meross.0 (19955) starting. Version 1.3.13 in /opt/iobroker/node_modules/iobroker.meross, node: v12.16.2, js-controller: 3.0.14
2020-04-21 20:37:54.159  - error: meross.0 (19955) Meross Connection Error: Error: 1004: A

Since the update to the new js-controller from 2.x (latest) I am getting this error on start.

**Comment by peterbaumert** [comment]
`2020-04-21 21:16:19.511  - debug: meross.0 (31112) Redis Objects: Use Redis connection: 127.0.0.1:9001
2020-04-21 21:16:20.352  - debug: meross.0 (31112) Objects client ready ... initialize now
2020-04-21 21:16:20.536  - debug: meross.0 (31112) Objects create System PubSub Client
2020-04-21 21:16:20.539  - debug: meross.0 (31112) Objects create User PubSub Client
2020-04-21 21:16:20.541  - debug: meross.0 (31112) Objects client initialize lua scripts
2020-04-21 21:16:20.814  - debug: meross.0 (31112) Objects connected to redis: 127.0.0.1:9001
2020-04-21 21:16:20.825  - debug: meross.0 (31112) objectDB connected
2020-04-21 21:16:20.829  - debug: meross.0 (31112) Redis States: Use Redis connection: 127.0.0.1:9000
2020-04-21 21:16:20.991  - debug: meross.0 (31112) States create User PubSub Client
2020-04-21 21:16:21.070  - debug: meross.0 (31112) States create System PubSub Client
2020-04-21 21:16:21.369  - debug: meross.0 (31112) States connected to redis: 127.0.0.1:9000
2020-04-21 21:16:21.373  - debug: meross.0 (31112) statesDB connected
2020-04-21 21:16:26.383  - debug: meross.0 (31112) Plugin sentry Initialize Plugin (enabled=true)
2020-04-21 21:16:28.006  - info: meross.0 (31112) starting. Version 1.3.13 in /opt/iobroker/node_modules/iobroker.meross, node: v12.16.2, js-controller: 3.0.14
2020-04-21 21:16:28.202  - debug: meross.0 (31112) HTTP-Call: {"url":"https://iot.meross.com/v1/Auth/Login","method":"POST","headers":{"Authorization":"Basic ","vender":"Meross","AppVersion":"1.3.0","AppLanguage":"EN","User-Agent":"okhttp/3.6.0"},"form":{"params":"","sign":"","timestamp":1587496588201,"nonce":""}}
2020-04-21 21:16:28.557  - debug: meross.0 (31112) connected set to false
2020-04-21 21:16:28.720  - debug: meross.0 (31112) HTTP-Response OK: {"apiStatus":1004,"sysStatus":0,"data":null,"info":"A","timeStamp":"2020-04-21 19:16:28"}
2020-04-21 21:16:28.736  - error: meross.0 (31112) Meross Connection Error: Error: 1004: A
2020-04-21 21:16:32.013  - debug: meross.0 (31112) system.adapter.admin.1: logging false`

**Comment by goohnie** [comment]
Nach Update auf js-controller 3.0.1.4 hab ich den Fehler auch.
Habe den Adapter deinstalliert und neu installiert.
Die Adapterkonfiguration lässt sich nicht mehr speichern.
Der Adapter bleibt auf gelb.

**Comment by goohnie** [comment]
meross.0	2020-04-22 21:52:52.421	debug	(27578) system.adapter.admin.0: logging true
meross.0	2020-04-22 21:52:28.742	error	(27578) Meross Connection Error: Error: 1000: Lack user
meross.0	2020-04-22 21:52:28.742	debug	(27578) HTTP-Response OK: {"apiStatus":1000,"sysStatus":0,"data":null,"info":"Lack user","timeStamp":"2020-04-22 19:52:28"}
meross.0	2020-04-22 21:52:28.531	debug	(27578) connected set to false
meross.0	2020-04-22 21:52:28.490	debug	(27578) HTTP-Call: {"url":"https://iot.meross.com/v1/Auth/Login","method":"POST","headers":{"Authorization":"Basic ","vender":"Meross","AppVersion":"1.3.0","AppLanguage":"EN","User-Agent":"okhttp/3.6
meross.0	2020-04-22 21:52:28.459	info	(27578) starting. Version 1.3.13 in /opt/iobroker/node_modules/iobroker.meross, node: v10.20.1, js-controller: 3.0.14
meross.0	2020-04-22 21:52:28.326	debug	(27578) Plugin sentry Initialize Plugin (enabled=true)
meross.0	2020-04-22 21:52:27.889	debug	(27578) statesDB connected
meross.0	2020-04-22 21:52:27.889	debug	(27578) States connected to redis: 0.0.0.0:9000
meross.0	2020-04-22 21:52:27.882	debug	(27578) States create System PubSub Client
meross.0	2020-04-22 21:52:27.881	debug	(27578) States create User PubSub Client
meross.0	2020-04-22 21:52:27.876	debug	(27578) Redis States: Use Redis connection: 0.0.0.0:9000
meross.0	2020-04-22 21:52:27.875	debug	(27578) objectDB connected
meross.0	2020-04-22 21:52:27.870	debug	(27578) Objects connected to redis: 0.0.0.0:9001
meross.0	2020-04-22 21:52:27.862	debug	(27578) Objects client initialize lua scripts
meross.0	2020-04-22 21:52:27.862	debug	(27578) Objects create User PubSub Client
meross.0	2020-04-22 21:52:27.861	debug	(27578) Objects create System PubSub Client
meross.0	2020-04-22 21:52:27.859	debug	(27578) Objects client ready ... initialize now
meross.0	2020-04-22 21:52:27.838	debug	(27578) Redis Objects: Use Redis connection: 0.0.0.0:9001
meross.0	2020-04-22 21:52:52.421	debug	(27578) system.adapter.admin.0: logging true

**Comment by elzershark** [comment]
Kann ich Bestätigen..

**Comment by Maxvil30** [comment]
Bei mir auch nur noch Gelb

**Comment by Jaaannis** [comment]
Bei mir auch, Adapter leider nicht mehr nutzbar.

**Comment by elzershark** [comment]
Du meinst der js-controller in der Version ist nicht kompatible.. Am Adapter ist alles i.O...

**Comment by goohnie** [comment]
Auch mit js-controller 3.0.1.8 dann wohl leider immer noch nicht kompatibel

**Comment by Apollon77** [comment]
Lack user   Sagt meross. Userdaten korrekt angegeben? Wie lang ist drin passwort?
Mach mal nur 10 Zeichen falls länger bitte

**Comment by elzershark** [comment]
Kann man nicht. Es funzt kein speichern. Es geht auch um "Neuinstallation" von Meross. Bestehendes Meross kann man speichern.

**Comment by elzershark** [comment]
Meross Adapter installiert. Upgrade js-controller. Speichern geht. Keine Funktion. Upload Meross Adapter. Einstellungen sind alle leer. Komplett leer. Normalerweise müssten Voreinstellungen drin sein

**Comment by Apollon77** [comment]
Das ist alles mega anstrenge und habe ich noch nie gesehen. Vor allem das ein upload alle Einstellungen löscht ... aber ok ist ja jetzt gelöst oder?!

**Comment by elzershark** [comment]
Meross 1.3.11 funzt mit js-controller: 3.x.x....

**Comment by elzershark** [comment]
Meross 1.3.13 funzt nicht mit js-controller: 3.x.x
Wichtig: Adapter darf nicht VOR js-controller installiert sein. Sonst "denkt" man, das es funktioniert.
Getestet mit iobroker frisch installiert. Latest. Meross installiert. Keine Speichern möglich

**Comment by elzershark** [comment]
js-controller: 2.2.10 + Meross 1.3.13 funzt

**Comment by Apollon77** [comment]
steht irgendetwas in der Browser Konsole wenn es nicht tut?

**Comment by elzershark** [comment]
Leider nein.

**Comment by elzershark** [comment]
b.z.w... sec..

**Comment by elzershark** [comment]
Meross 1.3.13 js-controller 2.2.10 läuft. 
upgrade js auf 3.0.18 

meross.0 | 2020-04-26 23:40:50.515 | error | (6581) Meross Connection Error: Error: 1004: A
-- | -- | -- | --

meross upload... meross funzt jetzt jetzt.
Alle Devices gefunden und connectet.
Aber in der Einstellung steht nichts drin.
Eingeben kann man nichts. Speichern geht nicht.

Meross Adapter deinstallier und gelöscht.
Neu installiert.
Direkt im Log...

meross.0 | 2020-04-26 23:47:46.472 | error | (6693) Meross Connection Error: Error: 1000: Lack user
-- | -- | -- | --

Speichern nicht möglich

**Comment by elzershark** [comment]
```
readDir | 2020-04-27 00:08:03.732 | warn | will not read this directory () in future versions: meross is not an object of type "meta"
-- | -- | -- | --
readDir | 2020-04-27 00:08:03.729 | warn | will not read this directory (widgets/meross.html/) in future versions: vis is not an object of type "meta"
readDir | 2020-04-27 00:08:03.723 | warn | will not read this directory (widgets/meross/) in future versions: vis is not an object of type "meta"
```

**Comment by elzershark** [comment]
Noch was anderes. Es gibt bestimmt noch andere Fehler mit anderenAdapter, wenn jemand upgrade js gemacht hat. Mann muss danach unbedingt

```
iobroker stop
iobroker upload all
```

machen.
Erst dann funktionieren/lassen sich andere Adapter upgraden/einstellen u.s.w.
Leider funzt das nicht mit dem Meross Adapter..

**Comment by Apollon77** [comment]
@elzershark sorry aber das ist Blödsinn. Upload all gehört im Normalfall nicht zu den nötigen Aktionen nach einem Controller update.   Beim Controller 3.0 hat das vor der 3.0.18 bei einzelnen Adaptern geholfen (3 nicht all). 

Ja es schadet auch nicht zu machen aber in 99.9% der Fälle hilft es auch nicht.

**Comment by elzershark** [comment]
JUp. Ich weis. Aber erst danach gingen die Adapter wieder..
Und noch was, was  super seltsam ist.. copy Paste in Einstellungen kann auch Probleme geben.
Ich hab das Gefühl das was mit "Passwörter" nicht stimmt. Erst beim "Tippen" von Einstellungen fuunzen einige Adapter..

**Comment by Apollon77** [comment]
Hä?

**Comment by elzershark** [comment]
Ja ,ich weiß. Super seltsam.. Das wieder beim Meross Adapter...

**Comment by elzershark** [comment]
30438) Meross Connection Error: Error: 1004: A

Bei Copy Paste..

Beim Tippen dfunzt es.. Aber das ausser acht lassen. Das kommt erst beim downgraden. Upload.. Upgraden.. u.s.w. zu Kompliziert.. Der Adapter "kriegt" man mit js-Controller 3.0.18 zum laufen. Aber sehr tricky

**Comment by elzershark** [comment]
Adapter iQontrol kriegt man nur geupgradet wenn man (js ist geupgradet)  upload macht. Dann kann man den Adapter upgraden..

**Comment by elzershark** [comment]
Also zur Zeit sieht das so aus..
js-controller auf 3.x.x.
Adapter upgraden falls angezeigt wird.
Danach diese Adapter upload machen. Oder halt alle auf einmal.
Besser ist alle. Da einige Adapter zwar grün sind, aber Fehler im log haben, oder es lassen sich sogar einige nicht mehr upgraden


Meross Adapter 1.3.13 u. js-controller 3.x.x.
Meross Adapter löschen. Danach deinstallieren.
downgrade js-controller auf 2.2.10
Meross  installieren.
Zum laufen bringen.
Wenn er läuft:
js-controller upgraden
Meross Adapter stoppen.
Uploaden.
Starten.
Läuft

**Comment by Apollon77** [comment]
Sorry nochmal aber solche Anleitungen helfen niemandem. Ansage ist: bitte warten bis ich es geprüft habe. Danke.

**Comment by Apollon77** [comment]
Bitte mal GANZ NORMAL mit Admin 4.0.9 und controller 3.0.19 testen oder mit nem controller 2.x. Bzw für die die eine Leerte Admin haben ist immer noch die Frage offen ob die Browser-Konsle irgendwas an Fehler anzeigt

**Comment by elzershark** [comment]
4.0.9 oder 4.1.1?

**Comment by elzershark** [comment]
Alles was unter controller 3.x.x. ist, funzt der Meross.
Ab 3.x.x. geht das speichern nicht. Fehler werden beim installieren nicht angezeigt.
Beim deinstallieren gibts Warnungen..

`npm uninstall iobroker.meross --error --prefix "/opt/iobroker" (System call)
npm
 WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.5 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
process exited with code 0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.5 (node_modules/osx-temperature-sensor):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
`

Kein speichern bei controller 3.0.19 Admin 4.0.9 o. 4.1.1.

**Comment by Jaaannis** [comment]
Keine Fehlermeldung, SAVE und SAVE AND CLOSE buttons sind nicht anklickbar. CLOSE funktioniert.

Node.js v12.16.2
NPM 6.14.4

Meross 1.3.13

Controller 3.0.19

Admin 4.1.1


Gruß

**Comment by Maxvil30** [comment]
Auch bei mir keine Fehlermeldung "Speichern" und "Speichern und Schließen" ohne Funktion, "Schließen" funktioniert.

Admin 4.1.1
js-controller 3.0.19
Node.js 12.16.2
NPM6.14.4
Meross 1.3.13

Grüße und Danke

**Comment by elzershark** [comment]
Vielleicht hilft das weiter.. Meross 1.3.12 funzt das Speichern..

reconnectet dauern die Devices. Keine Fehlermeldung

**Comment by Jaaannis** [comment]
1.3.12 funktioniert speichern bei mir auch.
Fehlermeldung bleibt dieselbe
(12425) Meross Connection Error: Error: 1004: A

Grüße

**Comment by Maxvil30** [comment]
1.3.12 Funktioniert bei mir Status Verbunden (Grün)
Admin 4.1.1
js-controller 3.0.19
Node.js 12.16.2
NPM6.14.4
**Meross 1.3.12**

**Comment by Jaaannis** [comment]
Bei mir jetzt auch mit einem 9 stelligen Passwort in Merros (vorher 16)

**Comment by elzershark** [comment]
1.3.12 gibt es keine Fehlermeldung. Der upload des Adapters hat gefehlt bei euch

**Comment by Maxvil30** [comment]
Ich hatte bei einem vorherigen Post mal auf ein 10 Zeichen Passwort gewechselt.
Upload fehlte bei mir nicht.

**Comment by peterbaumert** [comment]
Also das mit dem neuinstallieren und dann nicht speichern können habe ich auch @Apollon77 

`index_m.html?0:36 Uncaught TypeError: Cannot read property 'length' of undefined
    at encrypt (index_m.html?0:36)
    at r.<anonymous> (adapter-settings.js:259)
    at r.onack (index.js:83)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)
    at a.<anonymous> (index.js:83)
    at a.r.emit (index.js:83)
    at a.add (index.js:83)`

Die PW encrypt funktion hat da wohl ein Problem. Hat sich da was mit der nativen encrpytion geändert? Hatte da glaube was im jscontroller changelog gelesen?

**Comment by elzershark** [comment]
1.3.12 funzt tadellos. Man darf nur 1x Meross am laufen haben.

**Comment by elzershark** [comment]
Meross 1.3.12 controller 3.0.19.. läuft

**Comment by peterbaumert** [comment]
@Apollon77 denke mal der Fehler ist irgendwo hier: https://github.com/Apollon77/ioBroker.meross/blob/480d19a8157df07fc9b8a25a49deb5fc026d7cb8/admin/index_m.html#L103
die 1.3.12 geht. Ist wohl also wirklich was mit dem native/autoencrypt.

**Comment by itstartedwithac64** [comment]
ich bekomme auch keine Verbindung. Fehler:
meross.0 | 2020-04-29 18:51:44.295 | error | (35551) Meross Connection Error: Error: 1004: A

Mac Mini
js-controller 3.0.20
Admin 4.1.1
Node.js  12.16.3
Meross 1.3.11: SAVE und SAVE AND CLOSE buttonsfunktionieren aber keine Verbindung
            1.3.12, 1.3.13 SAVE und SAVE AND CLOSE buttons sind nicht anklickba und keine Verbindung

**Comment by Apollon77** [comment]
test 1.4.0 please

**Comment by elzershark** [comment]
funzt. Getestet stable und latest

**Comment by Apollon77** [comment]
1.4.0 ist maximal im latest.

**Comment by elzershark** [comment]
Nope. Über katze nach meross suchen und die Version 1.4.0 wird installiert. Egal ob stable oder latest

**Comment by Apollon77** [comment]
Dann ist deine Aussage seeeehr missverständlich!! Über die Kaste installierst du IMMER VON GitHub. Und damit an allen beiden episiotomies „vorbei“.

**Comment by elzershark** [comment]
Verständnis für mich: Das Testen 1.4.0.. Über Katze suchen, url von github eingeben oder per Befehl in Putty mit der Versionsnummer eingeben? Das Verstehe ich noch nicht genau, wenn man bestimmte Versionen testen soll..

**Comment by Apollon77** [comment]
Aaaaaalso: Im Falle hier sollte die 1.4.0 auch jetzt inzwischen im Latest Repo sein. GitHub kannst du faktsch keine spezifische Version testen weil Du immer letzten letzten ENtwicklungsstand testet. Und Github Install ignriert vollkommen was als repo eingestellt ist

**Comment by elzershark** [comment]
Ah, glaub habe verstanden. ok.. jo, 1.4.0 ist jetzt im "latest". Alles klaro 😀

**Comment by Apollon77** [comment]
1.4.0 war es noch nicht ... 1.4.1 sollte es jetzt aber haben

**Comment by cryptedx** [comment]
Also bei mir scheint nun dasselbe Problem zu sein.


meross.0 | 2021-03-01 19:56:34.664 | debug | (20208) system.adapter.admin.0: logging true
-- | -- | -- | --
meross.0 | 2021-03-01 19:54:59.870 | error | (20208) Meross Connection Error: Error: 1004: A
meross.0 | 2021-03-01 19:54:59.868 | debug | (20208) HTTP-Response OK: {"apiStatus":1004,"sysStatus":0,"data":null,"info":"A","timeStamp":1614624899}
meross.0 | 2021-03-01 19:54:56.631 | debug | (20208) connected set to false
meross.0 | 2021-03-01 19:54:56.531 | debug | (20208) HTTP-Call: {"url":"https://iot.meross.com/v1/Auth/Login","method":"POST","headers":{"Authorization":"Basic ","vender":"Meross","AppVersion":"1.3.0","AppLanguage":"EN","User-Agent":"okhttp/3.6
meross.0 | 2021-03-01 19:54:56.448 | info | (20208) starting. Version 1.5.1 in /opt/iobroker/node_modules/iobroker.meross, node: v12.20.0, js-controller: 3.2.7

**Comment by Apollon77** [comment]
This error usually means that the passwort is incorrect.

**Comment by Apollon77** [comment]
PS: adding a comment to an issue whcih is closed and solved since 6 months should bring what? ;-)

**Comment by cryptedx** [comment]
> This error usually means that the passwort is incorrect.

The password is working, I am using a password manager and I tested it with the app right now. It would be great to have a proper error message. "(20208) Meross Connection Error: Error: 1004: A" is  not very specific and helfpul.

My password was really strong. I have cut it down to 15 chars and without symbols. Now it is working... Very bad what meross is doing here...

> PS: adding a comment to an issue whcih is closed and solved since 6 months should bring what? ;-)

I want to bring it up again because it's the same error message. 

BTW: Smart Wi-Fi Light Strip MSL320HK / MSL320 is also working.

Thanks for makeing this adapter! :-)

**Comment by cryptedx** [comment]
> My password was really strong. I have cut it down to 15 chars and without symbols. Now it is working... Very bad what meross is doing here...

Das war meine Lösung.

**Comment by KPJ24** [comment]
Mein Password hat das bereits erfüllt. 
Habe es aber nochmal neu eingetragen. 
Nun geht es.

> 
> 
> > My password was really strong. I have cut it down to 15 chars and without symbols. Now it is working... Very bad what meross is doing here...
> 
> Das war meine Lösung.

Wer lesen kann, ist klar im Vorteil :-).
